apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.cpaas.redhat.com
webhooks:
  - name: validation.webhook.cpaas.redhat.com
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      url: "https://192.168.39.1/webhook/admission"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["cpaas.redhat.com"]
        apiVersions: ["v1alpha1"]
        resources: ["components"]
        scope: "Namespaced"
