apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.cpaas.redhat.com
webhooks:
  - name: components.webhook.cpaas.redhat.com
    sideEffects: None
    failurePolicy: Fail
    admissionReviewVersions: ["v1"]
    clientConfig:
      url: "https://192.168.39.1:8443/webhooks/validate/component"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["cpaas.redhat.com"]
        apiVersions: ["v1alpha1"]
        resources: ["components"]
        scope: "Namespaced"
