---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agogos-operator-view
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: agogos-operator
    namespace: agogos
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agogos-operator-admin
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["agogos.redhat.com"]
    resources: ["*"]
    verbs:
      [
        "get",
        "list",
        "watch",
        "create",
        "update",
        "patch",
        "delete",
        "deletecollection",
      ]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["*"]
    verbs:
      [
        "get",
        "list",
        "watch",
        "create",
        "update",
        "patch",
        "delete",
        "deletecollection",
      ]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["*"]
    verbs:
      [
        "get",
        "list",
        "watch",
        "create",
        "update",
        "patch",
        "delete",
        "deletecollection",
      ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agogos-operator-admin
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: agogos-operator-admin
subjects:
  - kind: ServiceAccount
    name: agogos-operator
    namespace: agogos
