---
apiVersion: v1
kind: Service
metadata:
  name: agogos-operator
  namespace: agogos
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
spec:
  ports:
    - name: http
      port: 7070
      targetPort: 7070
  type: ClusterIP
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agogos-operator
  namespace: agogos
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: agogos
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: agogos
    spec:
      containers:
        - name: service
          image: quay.io/cpaas/agogos-poc-operator:devel
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 7070
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
      serviceAccount: agogos-operator
