#!/bin/sh

set -xe

resource=${1}
workspace=${2}

if [ -z "${resource}" ]; then
    echo "No resource coordinate provided, exiting"
    exit 2
fi

if [ -z "${workspace}" ]; then
    echo "No workspace path provided, exiting"
    exit 2
fi

mkdir -p ${workspace}

exec kubectl get ${resource} -o json | tee ${workspace}/data.json
