#!/bin/sh

set -xe

cd /tmp

# Download binary and checksum
curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
curl -LO "https://dl.k8s.io/${KUBECTL_VERSION}/bin/linux/amd64/kubectl.sha256"

# Validate
echo "$(<kubectl.sha256) kubectl" | sha256sum --check

# Install
install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

rm -rf kubectl*
