= Examples

This page contains examples of common use cases for a
xref:reference:triggers/overview.adoc[_Trigger_].

== Component Resource

=== Rebuild a Component After Another Component is Built

[source,yaml]
----
apiVersion: agogos.redhat.com/v1alpha1
kind: Trigger
metadata:
  name: component-to-component
spec:
  events:
    - component:
        name: cpaas-test-brew-rpm
  target:
    kind: Component
    name: cpaas-test-brew-container
----

Once the `cpaas-test-brew-rpm` Component build finishes, the
`cpaas-test-brew-container` Component build will be started.

== Pipeline Resource

=== Run a Pipeline When a Component from a Group is Built

[source,yaml]
----
apiVersion: agogos.redhat.com/v1alpha1
kind: Trigger
metadata:
  name: group-to-pipeline
spec:
  events:
    - group:
        name: cpaas-test-example
  target:
    kind: Pipeline
    name: testing
----

After a Component from the `cpaas-test-example` Group is built, the
`testing` Pipeline will be run.

=== Run a Pipeline After a Specific Component Type is Built

[source,yaml]
----
apiVersion: agogos.redhat.com/v1alpha1
kind: Trigger
metadata:
  name: build-to-pipeline
spec:
  events:
    - build:
        filter: "body.component.spec.builder == 'brew' && body.component.spec.data.type == 'bundle'"
  target:
    kind: Pipeline
    name: test
----

Run the `test` Pipeline after a Component is built which meets following
requirements:

* `brew` builder was used
* within the configuration passed to the Builder, the `type` key was set to `bundle`

[NOTE]
====
The `test` Pipeline will be run for any Component that matches the criteria.
We don't "bind" the Trigger to any particular Component instance here.
====
