= Triggers

This guide will help you understand how Triggers work and what are the best
practices related to Triggers.

== Introduction

Every xref:concepts:builds.adoc[Build] or xref:concepts:pipelines.adoc[Pipeline] can be run manually but this is not sufficient for automated systems.

This is where Triggers come into play.

Triggers are a way to define *when* a particular Pipeline (or Build) should be run.

A Trigger is a binding between some event in the system and some action. Defined action
is performed only when an event meets the required criteria defined by the Trigger
making Triggers event filters.

Most common actions are:

* running a pipeline after a build is completed
* running next pipeline after some pipeline finishes

Triggers are evaluated for every event within the system. This is shown in the
diagram below.

[graphviz,eventing,svg]
....
digraph G {
rankdir="LR";
splines="false";
graph [fontname="helvetica",ranksep=1,nodesep=0.6];
node [fontname="helvetica",shape="box",style="rounded",fontsize="12"];
edge [fontname="helvetica",arrowsize="1",penwidth="1",fontsize="10"];

event1 [label="Event",color="#a83232",penwidth="2"];
event2 [label="Event",color="#328da8",penwidth="2"];
event3 [label="Event"];
trigger1 [label="Trigger",color="#328da8",penwidth="2"];
trigger2 [label="Trigger",color="#a83232",penwidth="2"];
component [style="",shape="parallelogram",label="Component",color="#328da8",penwidth="2"];
pipeline [style="",shape="parallelogram",label="Pipeline",color="#a83232",penwidth="2"];

event1 -> trigger1 [style="dashed"];
event1 -> trigger2 [color="#a83232",penwidth="2"];
event2 -> trigger1 [color="#328da8",penwidth="2"];
event2 -> trigger2 [style="dashed"];
event3 -> trigger1 [style="dashed"];
event3 -> trigger2 [style="dashed"];

// event1 -> pipeline [style="dashed",color="#dddddd",label="Triggers"];
// event2 -> component [style="dashed",color="#dddddd",label="Triggers"];

trigger1 -> component [color="#328da8",penwidth="2",label="Build"];
trigger2 -> pipeline [color="#a83232",penwidth="2",label="Run"];
}
....

There are multiple event types within the system and there are multiple Trigger types
as well to cover these cases.

Triggers are defined using the xref:concepts:triggers.adoc[Trigger resource].

[#multiple-triggers]

== Multiple Triggers

Every resource that supports triggers can have multiple triggers defined. Multiple
triggers specified on the same resource are *evaluated separately*. This means that
every time a _Trigger_ defined on the resource will be satisfied -- the resource
wil be triggered.

WARNING: In case of misconfiguration -- resource can be triggered *multiple times* because of the same event.

== Supported Target Resources

Resource that can be defined as Trigger targets:

* xref:concepts:components.adoc[Component] -- a new build will be started
* xref:concepts:pipelines.adoc[Pipeline] -- a new run will be executed

== Examples

The xref:reference:triggers/examples.adoc[examples page] contains examples usage of _Triggers_.
