= Internals

include::common:partial$draft.adoc[]

== Internal Representation of Triggers

Triggers are implemented internally using link:https://knative.dev/docs/eventing/[Knative Eventing]
and link:https://tekton.dev/docs/triggers/[Tekton Triggers]. This section
explains how these projects are used to deliver Agogos Triggers functionality.

When an Agogos Trigger is created, the object is validated by Agogos to ensure
that it contains valid content. Once this is done, Kubernetes creates
the resource.

Agogos operator is notified about the new Trigger resource. The first thing it
does is to create a Tekton link:https://tekton.dev/docs/triggers/triggers/[Trigger]
which is the representation of the
Agogos Trigger in Tekton world.

[NOTE]
====
There's more behind the scenes!

Tekton Trigger uses specific
link:https://tekton.dev/docs/triggers/triggertemplates/[TriggerTemplate]
that is responsible for creating new
link:https://tekton.dev/docs/pipelines/pipelineruns/[PipelineRun] resources.
Besides the template a link:https://tekton.dev/docs/triggers/triggerbindings/[TriggerBinding]
is used which provides required parameters to the template based on the event.
====

Last part is to create or update Tekton link:https://tekton.dev/docs/triggers/eventlisteners/[EventListener].
Such listener is responsible for receiving events from Knative and evaluating
registered triggers.

Above flow can be seen in the sequence diagram below.

[seqdiag,trigger,svg]
.Agogos Trigger creation
....
seqdiag {

user [label="User"];
k8s [label="Kubernetes"];
agogos [label="Agogos"];
tkn_triggers [label="Tekton Triggers"];

user -> k8s [label="Agogos Trigger"];

k8s => agogos [label="validate(Agogos Trigger)", return="ok"];
k8s -> k8s [label="Create resource"];
user <-- k8s [label="ok"];
k8s -> agogos [label="Agogos Trigger"] {
    agogos => tkn_triggers [label="create(Trigger)", return="ok"];
    agogos => tkn_triggers [label="update(EventListener)", return="ok"];
}

}
....

== EventListener Instances

#TODO#

In Agogos we use multiple Tekton EventListeners to handle incoming events.

== Knative Eventing Usage

Tekton EventListener is handling events that come from Knative.
Every event the Knative Broker receives is filtered based on the type
of the event and forwarded to appropriate EventListener.

NOTE: See the xref:events/index.adoc#eventing-overview[overview diagram].

#TODO#

== Resource Workflow

Let's see now what's happening underneath.

When Agogos operator is run it creates a Tekton Triggers EventListener responsible
for handling any events related to Component builds in the system.

[source,yaml]
----
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: component-build
  namespace: agogos
spec:
  serviceAccountName: agogos-el
----

After the Trigger is created within Agogos an appropriate Tekton Triggers Trigger resource is created:

[source,yaml]
----
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  # Generated name based on the Agogos trigger name
  name: container-main-bkowbw1tloi
  namespace: agogos
spec:
  # Specifies filter to trigger only when a specific build is finished
  interceptors:
    - cel:
        filter: "body.component.metadata.name == 'container-dep'"
  # Use the correct binding...
  bindings:
    - ref: componentbuild-to-componentbuild
  # And template
  template:
    ref: componentbuild
----

The Tekton EventListener needs to be updated to see the new Trigger:

[source,yaml]
----
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: component-build
  namespace: agogos
spec:
  serviceAccountName: agogos-el
  triggers:
    - triggerRef: container-main-bkowbw1tloi
----

Agogos deploys the required TriggerTemplate and TriggerBinding as well.

[source,yaml]
.Tekton Triggers TriggerTemplate to build a Component
----
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: componentbuild
  namespace: agogos
spec:
  params:
    - name: component
      description: The Component name to build
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.component)-
        namespace: default
      spec:
        pipelineRef:
          name: $(tt.params.component)
        serviceAccountName: agogos
        workspaces:
          - name: ws
            volumeClaimTemplate:
              apiVersion: v1
              kind: PersistentVolumeClaim
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: standard
----

[source,yaml]
.Tekton Triggers TriggerBinding to provide Component name to build
----
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: componentbuild-to-componentbuild
  namespace: agogos
spec:
  params:
    - name: component
      value: $(body.component.metadata.name)
----
