= Overview

This guide will help you understand how Triggers work and what are the best
practices related to Triggers.

== Introduction

Every
xref:concepts:builds.adoc[Build]
or
xref:concepts:pipelines.adoc[Pipeline]
can be run manually but this is not sufficient for automated systems.
This is where
xref:concepts:triggers.adoc[Triggers]
come into play.

Triggers are a way to define *when* a particular Pipeline (or Build) should
be run.

A Trigger is a binding between some event in the system and some action.
Defined action is performed only when an event meets the required criteria
defined by the Trigger.

Most common actions are:

* running a pipeline after a build is completed
* running next pipeline after some pipeline finishes

Triggers are evaluated for every event within the system. This is shown in the
diagram below.

[graphviz,eventing,svg]
....
digraph G {
rankdir="LR";
splines="false";
graph [fontname="helvetica",ranksep=1,nodesep=0.6];
node [fontname="helvetica",shape="box",style="rounded",fontsize="12"];
edge [fontname="helvetica",arrowsize="1",penwidth="1",fontsize="10"];

event1 [label="Event",color="#a83232",penwidth="2"];
event2 [label="Event",color="#328da8",penwidth="2"];
event3 [label="Event"];
trigger1 [label="Trigger",color="#328da8",penwidth="2"];
trigger2 [label="Trigger",color="#a83232",penwidth="2"];
component [style="",shape="parallelogram",label="Component",color="#328da8",penwidth="2"];
pipeline [style="",shape="parallelogram",label="Pipeline",color="#a83232",penwidth="2"];

event1 -> trigger1 [style="dashed"];
event1 -> trigger2 [color="#a83232",penwidth="2"];
event2 -> trigger1 [color="#328da8",penwidth="2"];
event2 -> trigger2 [style="dashed"];
event3 -> trigger1 [style="dashed"];
event3 -> trigger2 [style="dashed"];

// event1 -> pipeline [style="dashed",color="#dddddd",label="Triggers"];
// event2 -> component [style="dashed",color="#dddddd",label="Triggers"];

trigger1 -> component [color="#328da8",penwidth="2",label="Build"];
trigger2 -> pipeline [color="#a83232",penwidth="2",label="Run"];
}
....

There are multiple event types within the system and there are multiple Trigger types
as well to cover these cases.

[TIP]
====
To understand better Triggers you may want to read about
xref:events/overview.adoc[Events]
first.
====

Let's consider following Trigger definition:

[source,yaml]
----
apiVersion: agogos.redhat.com/v1alpha1
kind: Trigger
metadata:
  name: container-main
spec:
  events:
    - build:
        component: container-dep
  target:
    kind: Component
    name: container-main
----

It creates a binding between a Component build event and another component
so that when a Component with name `container-dep` builds successfully, the
Trigger will kick the `container-main` Component build.

[#multiple-triggers]

== Multiple Triggers

Every resource that supports triggers can have multiple triggers defined. Multiple
triggers specified on the same resource are *evaluated separately*. This means that
every time a Trigger defined on the resource will be satisfied -- the resource
will be triggered.

[WARNING]
====
If the triggers are configured incorrectly -- resources can be triggered
*multiple times* by the same event.
====

== Supported Target Resources

Resource that can be defined as Trigger targets:

* xref:concepts:components.adoc[Component]
 -- a new build will of specified Component be started
* xref:concepts:pipelines.adoc[Pipeline]
 -- specified Pipeline will be run

== Examples

The
xref:reference:triggers/examples.adoc[examples page]
contains examples usage of Triggers.

== More Information

If you want to know more on how Triggers are implemented, we have a
xref:triggers/internals.adoc[document describing this].
