build native executable:
  artifacts:
    paths:
      - $FOLDER/target/*-runner
  image:
    name: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java17
    entrypoint: ["/bin/sh", "-c"]
  parallel:
    matrix:
      - FOLDER:
          #- cli
          #- interceptors
          - operator
          #- webhooks
  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#      changes:
#        - .gitlab-ci.yml
#        - core/**/*
#        - $FOLDER/**/*
  script:
    - ./mvnw package -pl $FOLDER -am -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.native-image-xmx=8g -s settings.xml
  stage: build
  tags:
    - native-images
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    MAVEN_MIRROR_URL: "https://agogos-nexus.apps.ocp4.prod.psi.redhat.com/repository/maven-public"
    KUBERNETES_CPU_REQUEST: "2"
    KUBERNETES_CPU_LIMIT: "2"
    KUBERNETES_MEMORY_REQUEST: "2Gi"
    KUBERNETES_MEMORY_LIMIT: "8Gi"

build and push image:
  image:
    name: gcr.io/kaniko-project/executor:v1.12.1-debug
    entrypoint: [""]
  parallel:
    matrix:
      - FOLDER:
          #- interceptors
          - operator
          #- webhooks
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#      changes:
#        - .gitlab-ci.yml
#        - core/**/*
#        - webhooks/**/*
  script:
    # This dockerconfig is for the agogos+extensions_pusher robot account
    # If you add a new image, that robot account needs new permissions
    - mv ${QUAY_IO_DOCKERCONFIG} /kaniko/.docker/config.json
    - /kaniko/executor --context "$FOLDER" --dockerfile "src/main/docker/Dockerfile.native" --destination "quay.io/agogos/agogos-$FOLDER:test"
  stage: deploy
  tags:
    - docker
