---
.common-variables:
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    MAVEN_MIRROR_URL: "https://agogos-nexus.apps.ocp4.prod.psi.redhat.com/repository/maven-public"
    KUBERNETES_CPU_REQUEST: "2"
    KUBERNETES_CPU_LIMIT: "2"
    KUBERNETES_MEMORY_REQUEST: "2Gi"
    KUBERNETES_MEMORY_LIMIT: "8Gi"

.build-native-image:
  extends: .common-variables
  artifacts:
    paths:
      - $IMAGE/target/*-runner
  image:
    name: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java17
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab-ci.yml
        - core/**/*
        - $IMAGE/**/*
  script:
    - |-
            ./mvnw package -pl $IMAGE -am -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.native-image-xmx=9g -s settings.xml
  stage: build
  tags:
    - native-images

build-interceptors:
  extends: .build-native-image
  variables:
    IMAGE: interceptors

build-operator:
  extends: .build-native-image
  needs:
    job: build-interceptors
    optional: true
  variables:
    IMAGE: operator

build-webhooks:
  extends: .build-native-image
  needs:
    job: build-operator
    optional: true
  variables:
    IMAGE: webhooks

push-native-image:
  needs:
    - job: build-interceptors
      optional: true
    - job: build-operator
      optional: true
    - job: build-webhooks
      optional: true
  image:
    name: gcr.io/kaniko-project/executor:v1.12.1-debug
    entrypoint: [""]
  parallel:
    matrix:
      - FOLDER:
          - interceptors
          - operator
          - webhooks
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab-ci.yml
        - core/**/*
        - $FOLDER/**/*
  script:
    # This dockerconfig is for the agogos+extensions_pusher robot account
    # If you add a new image, that robot account needs new permissions
    - mv ${QUAY_IO_DOCKERCONFIG} /kaniko/.docker/config.json
    - /kaniko/executor --context "$FOLDER" --dockerfile "src/main/docker/Dockerfile.native" --destination "quay.io/agogos/agogos-$FOLDER:test"
  stage: deploy
  tags:
    - docker

.build-native-executable:
  extends: common-variables
  artifacts:
    paths:
      - $EXECUTABLE/target/*-runner
  image:
    name: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java17
    entrypoint: ["/bin/sh", "-c"]
  parallel:
    matrix:
      - FOLDER:
          - cli
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .gitlab-ci.yml
        - core/**/*
        - $EXECUTABLE/**/*
  script:
    - |-
            ./mvnw deploy -pl $EXECUTABLE -am -Pnative -Dquarkus.native.native-image-xmx=9g -Dnexus.username=$NEXUS_USER -Dnexus.password=$NEXUS_PASSWORD -s settings.xml
  stage: build
  tags:
    - native-images

build-cli:
  extends: .build-native-executable
  variables:
    IMAGE: cli
