
lint:commit:
  stage: static-analysis
  image: registry.access.redhat.com/ubi9/nodejs-18-minimal:latest
  tags: [docker]
  script:
    - npm i --loglevel silent
    - echo "${CI_MERGE_REQUEST_TITLE}" | npx commitlint --config ${CI_PROJECT_DIR}/.commitlintrc.js
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
