site:
  title: Agogos
  url: https://agogos.pages.redhat.com/agogos/
  start_page: docs::index.adoc
content:
  sources:
    - url: https://gitlab.cee.redhat.com/agogos/agogos.git
      branches: main
      start_path: docs
      edit_url: false
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
