site:
  title: Agogos
  url: http://127.0.0.1:4000/
  start_page: docs::index.adoc
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs
      edit_url: false
ui:
  supplemental_files: ./docs/ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    warning-caption: ⚠️ warning
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
