site:
  title: Agogos
  url: https://agogos.pages.redhat.com/agogos/
  start_page: docs::index.adoc
content:
  sources:
    - url: https://gitlab.cee.redhat.com/agogos/agogos.git
      branches: main
      start_path: docs
      edit_url: false
ui:
  supplemental_files: ./docs/ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    warning-caption: ⚠️ warning

antora:
  extensions:
  - require: '@antora/lunr-extension'
  - require: ./docs/custom_extensions/lunr-patch.js
