site:
  title: Agogos
  url: http://127.0.0.1:4000/
  start_page: docs::index.adoc
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.cee.redhat.com/agogos/antora-ui/-/jobs/artifacts/main/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    warning-caption: ⚠️ warning
  extensions:
    - asciidoctor-kroki
