= Development Mode

This tutorial shows you how to run a simple component build on Agogos using Minikube.

== Objectives

* Install Agogos into a Minikube cluster
* Define a simple component to build
* Build the component

== Before you begin
This tutorial assumes you have already setup `minikube`, `kubectl` and, at
least, OpenJDK 11 . See
link:https://minikube.sigs.k8s.io/docs/start/[minikube start],
link:https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[kubectl] and
link:https://openjdk.org/[OpenJDK]
for installation instructions.

== Untrusted Certificates
We need Minikube to trust the Red{nbsp}Hat root certificates as Agogos interacts
with many different internal services. The internal certificates are self-signed,
so they are considered
link:https://minikube.sigs.k8s.io/docs/handbook/untrusted_certs/[unstrusted certificates].
Run:

[source,bash]
----
mkdir $HOME/.minikube/certs/
wget -O $HOME/.minikube/certs/RH-IT-Root-CA.crt https://certs.corp.redhat.com/certs/2015-IT-Root-CA.pem
wget -O $HOME/.minikube/certs/2022-IT-Root-CA.pem https://certs.corp.redhat.com/certs/2022-IT-Root-CA.pem
----

== Create a Minikube Cluster

[source,bash]
----
minikube start --driver=kvm2 --cpus=4 --memory=6g --disk-size=30GB --kubernetes-version=1.21.14 --embed-certs
----

Minikube configures your [filename]`$HOME/.kube/config` to use the newly created
cluster. `kubectl` supports different contexts, see
link:https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[organize cluster access]
for detailed information.

Use `kubectl config current-context` to see the context you are working in. It
should return `minikube`.

== Open Firewall Ports From Minikube To The Host
The Kubernetes cluster needs to contact Agogos' Webhooks for resource validation.
In development mode this means that Minikube needs to access some host ports. Here,
we provide information about how to achieve when using `firewalld`. Make
sure `firewalld` is running, then run:

[source,bash]
----
sudo firewall-cmd --permanent --zone=libvirt --add-port=8443/tcp  # This opens the port after restart
sudo firewall-cmd --zone=libvirt --add-port=8443/tcp  # This opens the port immediately
----

To open the port 8443 from the Minikube Virtual Machine to localhost.

== Installing Agogos in Development Mode
In the root of the repository, run:

[source,bash]
----
./mvnw clean package -D skipTests
----

This command compiles all the Agogos packages. To install the Agogos, run:

[source,bash]
----
java -jar cli/target/quarkus-app/quarkus-run.jar adm install --profile dev --namespace default
----

This command install Tekton, Knative Eventing and the Agogos CustomResourceDefinitions,
as well as the Agogos webhooks. It also creates a self-signed certificate
([filename]`key.pem` and [filename]`webhooks.crt`) to encrypt the Agogos
webhooks endpoint.

== Forwarding the Knative Eventing Broker Ingress
Agogos sends events to the Knative Eventing service. In this tutorial, we run
Agogos locally, so the Knative Eventing service needs to be available at localhost.
Run:

[source,bash]
----
kubectl -n knative-eventing port-forward service/broker-ingress 8111:http
----

This command forwards the HTTP port of the service to the port `8111` on
localhost. It is a blocking command, so run it in a separate shell.

== Running Agogos
Agogos has two components: operator and webhooks. You need to run them in
separate shells:

[source,bash]
.Running the Operator
----
./mvnw quarkus:dev -pl operator -am
----

[source,bash]
.Running the Webhooks
----
./mvnw quarkus:dev -pl webhooks -am
----

Quarkus runs a debug port by default. Since we are running two instances of
Quarkus, an error is printed:

[source,text]
----
[ERROR] Port 5005 in use, not starting in debug mode
----

If you want the Quarkus debugger for both processes, you need to change the debug
port. See the Quarkus documentation for detailed information.

[TIP]
====
You can start Agogos directly from Visual Studio Code, see the
xref:ide.adoc[IDE guide].
====

== Creating Agogos Resources
When you have Agogos up and running, run:

[source,bash]
----
kubectl apply -f https://gitlab.cee.redhat.com/api/v4/projects/agogos%2Fbuilder-dummy/repository/files/v1%2Fdummy.yaml/raw?ref=main
----

This command registers the Agogos dummy builder and the Tekton dummy
ClusterTask. Retrieve the builder using:

[source,bash]
----
kubectl get builders
# or
java -jar cli/target/quarkus-app/quarkus-run.jar -v builders list
----

Next, create a file called [filename]`component.yml`:

[source,yaml]
----
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: dummy
spec:
  build:
    builderRef:
      kind: Builder
      name: dummy-v1
----

And apply it with `kubectl`:

[source,bash]
----
kubectl apply -f component.yml
----

And then run your first build using the Agogos CLI:

[source,bash]
----
$ java -jar cli/target/quarkus-app/quarkus-run.jar -v components list
NAME      STATUS    CREATED
dummy     Ready     2023-04-05 08:51:13

$ java -jar cli/target/quarkus-app/quarkus-run.jar -v components build dummy
💖 About

Name:           dummy-xv5jx

🎉 Status

Status:         New 
Reason:         N/A
Created:        2023-04-05 08:55:49
Started:        N/A
Finished:       N/A
----

You can check its result running:

[source,bash]
----
java -jar cli/target/quarkus-app/quarkus-run.jar -v builds list
NAME            STATUS       CREATED
dummy-xv5jx     Finished     2023-04-05 08:55:49
----
