= Development Mode

This tutorial shows you how to run and use Agogos with Minikube.

== Objectives

* Install Agogos into a Minikube cluster
* Define a simple component to build
* Build the component

== Before you begin
This tutorial assumes you have already setup `minikube`, `kubectl`, `OpenJDK 17`
and `Hashicorp Vault`. See the following for installation instructions:

* link:https://minikube.sigs.k8s.io/docs/start/[minikube start]
* link:https://minikube.sigs.k8s.io/docs/drivers/kvm2/[Linux: kvm2 driver for minikube]
* link:https://minikube.sigs.k8s.io/docs/drivers/hyperkit/[macOS: hyperkit driver for minikube]
* link:https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[kubectl]
* link:https://openjdk.org/[OpenJDK]
* link:https://developer.hashicorp.com/vault/downloads/[Hashicorp Vault]

[TIP]
====
* The `minikube` guide for the kvm2 driver contains a useful
link:https://minikube.sigs.k8s.io/docs/drivers/kvm2/#troubleshooting[troubleshooting guide.]
* `Hashicorp Vault`: Please contact the 
link:https://mail.google.com/chat/u/0/#chat/space/AAAA2w955F8[Agogos development team]
to ensure that you have the necessary access to the vault.
====

== Untrusted Certificates
We need Minikube to trust the Red{nbsp}Hat root certificates as Agogos interacts
with many different internal services. The internal certificates are self-signed,
so they are considered
link:https://minikube.sigs.k8s.io/docs/handbook/untrusted_certs/[untrusted certificates].
Run:

[source,bash]
----
mkdir $HOME/.minikube/certs/
wget -O $HOME/.minikube/certs/RH-IT-Root-CA.crt https://certs.corp.redhat.com/certs/Current-IT-Root-CAs.pem
----

[TIP]
====
Your system may need to trust the Red{nbsp}Hat self-signed certificates as well. See the
link:https://source.redhat.com/groups/public/identity-access-management/it_iam_pki_rhcs_and_digicert/faqs_new_corporate_root_certificate_authority[FAQ on internal certificates]
for installation instructions.
====

== Create a Minikube Cluster

[source,bash]
----
minikube start --driver=kvm2 --kubernetes-version=1.26.1 --cpus=4 --memory=6g --disk-size=30GB --embed-certs
----

[IMPORTANT]
====
If your system is macOS, use `--driver=hyperkit`.
====

Minikube configures your [filename]`$HOME/.kube/config` to use the newly created
cluster. `kubectl` supports different contexts, see
link:https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[organize cluster access]
for detailed information.

Use `kubectl config current-context` to see the context you are working in. It
should return `minikube`.

== Open Firewall Ports From Minikube To The Host
The Kubernetes cluster needs to contact Agogos' Webhooks for resource validation.
In development mode this means that Minikube needs to access some host ports. Here,
we provide information about how to open the ports when using Firewalld.

Make sure the process `firewalld` is running, then run:

[source,bash]
----
sudo firewall-cmd --permanent --zone=libvirt --add-port=8443/tcp  # This opens the port after restart
sudo firewall-cmd --zone=libvirt --add-port=8443/tcp  # This opens the port immediately
----

To open the port 8443 from the Minikube Virtual Machine to localhost.

[WARNING]
====
Sometimes Firewalld is disabled and is not started automatically. Run
[command]`sudo systemctl start firewalld` to start it.
====

== Installing Agogos in Development Mode

This procedure installs Tekton, Knative Eventing, and the Agogos CustomResourceDefinitions,
as well as the Agogos Webhooks. It also creates self-signed certificates
to encrypt the Agogos webhooks endpoint. These certificates are automatically
used by Agogos.

. Clone the
link:https://gitlab.cee.redhat.com/agogos/agogos[Agogos]
repository
. In the root folder of the cloned repository compile the project using Maven:
+
[source,bash]
----
$ ./mvnw clean package -D skipTests
----

. Create an alias [command]`agogosctl-dev` to execute the development Java jar file:
+
[source,bash]
----
alias agogosctl-dev="java -jar ${PWD}/cli/target/quarkus-app/quarkus-run.jar"
----
+
Make sure your alias does not contain the `PWD` variable:
+
[source,bash]
----
alias agogosctl-dev
----

. Install Agogos on the Minikube cluster using the `dev` profile:
+
[source,bash]
----
QUARKUS_PROFILE=dev agogosctl-dev adm install --profile dev
----
. Forward the Knative Eventing service to the port `8111` in `localhost`:
+
[source,bash]
----
kubectl -n knative-eventing port-forward service/broker-ingress 8111:http
----

== Running Agogos
Agogos has different components. You need to keep them running in
separate shells (press 'q' to exit their processes):

[source,bash]
.Running the Operator
----
./mvnw quarkus:dev -pl operator -am
----

[source,bash]
.Running the Webhooks
----
./mvnw quarkus:dev -pl webhooks -am
----

[source,bash]
.Running the Interceptors
----
./mvnw quarkus:dev -pl interceptors -am
----

Quarkus runs a debug port by default. Since we are running three instances of
Quarkus, an error is printed:

[source,text]
----
[ERROR] Port 5005 in use, not starting in debug mode
----

If you want the Quarkus debugger for both processes, you need to change the debug
port. See the Quarkus documentation for detailed information.

[TIP]
====
You can start Agogos directly from Visual Studio Code, see the
xref:ide.adoc[IDE guide].
====

== Installing a Builder
After installing Agogos, you need to install a Builder in order to build Components.
We keep our Builders and other Extensions in the
link:https://gitlab.cee.redhat.com/agogos/extensions-internal[Agogos Extensions Internal repository].
To install the Builder "Dummy v1" run:

[source,bash]
----
# Setup vault environment variables
export VAULT_ADDR=https://vault.corp.redhat.com:8200
export VAULT_NAMESPACE=exd
export HV_TOKEN=$(vault login -method=oidc -field=token 2>/dev/null)

# Clone and run a python script to install a builder
git clone https://gitlab.cee.redhat.com/agogos/extensions-internal.git
cd extensions-internal
pipenv install --dev
pipenv shell
python install/install.py builders/dummy/v1/ --hv-token=${HV_TOKEN}
----

[NOTES]
====
* If the process fails trying to create a fork process, set the
  following variable before running: 
  [command]`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`.
* If you run into permission issues, ask the Agogos team to add you to the proper
  Rover team and refresh your token by logging into HashiCorp Vault again.
* The process is the same for any other Builder or Extension: change the folder
  passed to the [command]`install/install.py` script.
====

This command registers the Agogos Dummy Builder in the cluster. Retrieve the
builder using:

[source,bash]
----
kubectl get builders
# or
java -jar cli/target/quarkus-app/quarkus-run.jar -v builders list
----

To use the Builder, you need to initialize a namespace and configure it
to use the `dummy-v1` Builder:

[source,bash]
----
java -Dquarkus.profile=dev -jar cli/target/quarkus-app/quarkus-run.jar adm init --namespace tests --extensions dummy-v1
----

This command creates service accounts, rolebindings and configuration maps. The
command also copies builder resources. Then change the namespace [command]`kubectl`
uses by default:

[source,bash]
----
kubectl config set-context --current --namespace tests
----

[WARNING]
====
The Agogos CLI uses the namespace configured in your current [command]`kubectl` context.
====

== Building Components
Next, write the following Components to a YAML file and apply them using 
[command]`kubectl apply -f your-file.yml`:

[source,yaml]
----
include::example$development-mode/components.yaml[]
----

And then run a build using the Agogos CLI:

[source,bash]
----
$ java -jar cli/target/quarkus-app/quarkus-run.jar -v components list
NAME          STATUS    CREATED
dummy-1       Ready     YYYY-MM-DD HH:MM:SS
dummy-2       Ready     YYYY-MM-DD HH:MM:SS
dummy-3       Ready     YYYY-MM-DD HH:MM:SS

$ java -jar cli/target/quarkus-app/quarkus-run.jar -v components build dummy-1
💖 About

Name:       dummy-1-cn2rj

🎉 Status

Status:     Running
Reason:     Build is running
Created:    YYYY-MM-DD HH:MM:SS
Started:    YYYY-MM-DD HH:MM:SS
Finished:   N/A
Duration:   0 minute(s)
----

After a while, `dummy-1` and its dependents should be finished:

[source,bash]
----
$ java -jar cli/target/quarkus-app/quarkus-run.jar -v builds list
NAME                STATUS       CREATED
dummy-1-cn2rj       Finished     YYYY-MM-DD HH:MM:SS
dummy-2-z22dj       Finished     YYYY-MM-DD HH:MM:SS
dummy-3-mwv9q       Finished     YYYY-MM-DD HH:MM:SS
----


== Building Groups
Agogos supports Groups to build Components and triggers the builds of their
dependencies. Create a YAML file with the following content and apply it to your
namespace using [command]`kubectl apply -f your-group-file.yml`:

[source,yaml]
----
include::example$development-mode/components-and-group.yaml[]
----

Then build the Group `group-1` using the Agogos CLI:

[source,bash]
----
$ java -jar cli/target/quarkus-app/quarkus-run.jar -v group execute group-1
💖 About

Name:       group-1-s95mg

Components: Name                            Status    Started              Completed            Duration
            dummy-1-a                       New       N/A                  N/A
            dummy-1-b                       New       N/A                  N/A

🎉 Status

Status:     Running
Reason:     N/A
Created:    YYYY-MM-DD HH:MM:SS
Started:    YYYY-MM-DD HH:MM:SS
Finished:   N/A
Duration:   0 minute(s)
----

After a while, the Group Components and their dependents should be finished:

[source,bash]
----
$ java -jar cli/target/quarkus-app/quarkus-run.jar -v builds list
NAME                STATUS       CREATED
dummy-1-a-chb7x     Finished     YYYY-MM-DD HH:MM:SS
dummy-1-b-lfwvr     Finished     YYYY-MM-DD HH:MM:SS
dummy-2-g7zwz       Finished     YYYY-MM-DD HH:MM:SS
dummy-3-t89hc       Finished     YYYY-MM-DD HH:MM:SS
----
