= Development Mode

This tutorial shows you how to run and use Agogos with Minikube.

== Objectives

* Install Agogos in development mode into a Minikube cluster
* Define Agogos Components and build them

== Before you begin
Before beginning this tutorial, ensure `minikube`, `kubectl`, `OpenJDK 17` are set up.
See the following for installation instructions:

* link:https://minikube.sigs.k8s.io/docs/start/[minikube start]
** link:https://minikube.sigs.k8s.io/docs/drivers/kvm2/[Linux: kvm2 driver for minikube]
** link:https://minikube.sigs.k8s.io/docs/drivers/hyperkit/[macOS: hyperkit driver for minikube]
* link:https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[kubectl]
* link:https://openjdk.org/projects/jdk/17/[OpenJDK 17]

[TIP]
====
* Recommend to start with link:https://hdn.corp.redhat.com/fedora-csb-isos/[CBS Fedora 39]
+
[source,bash]
----
sudo dnf install @virtualization docker
sudo systemctl enable --now libvirtd
sudo usermod -aG libvirt $USER
sudo usermod -aG docker $USER
newgrp libvirt
newgrp docker
----
* The `minikube` guide for the kvm2 driver contains a useful
link:https://minikube.sigs.k8s.io/docs/drivers/kvm2/#troubleshooting[troubleshooting guide].
====

== Open Firewall Ports from Minikube to the Host
The Kubernetes cluster needs to contact Agogos' Webhooks to validate resources.
In development mode, the Minikube cluster needs to access some host ports.

[NOTE]
====
If your system does not use `firewalld`, continue with this guide and if you
encounter any issues contact the Agogos development team.
====

. Make sure the process `firewalld` is running:
+
[source,bash]
----
systemctl status firewalld
----
+
If it is not running, run the following command:
+
[source,bash]
----
sudo systemctl start firewalld
----

. Immediately open port `8443`:
+
[source,bash]
----
sudo firewall-cmd --zone=libvirt --add-port=8443/tcp
----

. Configure `firewalld` to permanently open port `8443`:
+
[source,bash]
----
sudo firewall-cmd --permanent --zone=libvirt --add-port=8443/tcp
----

== Starting the Minikube Cluster
These commands download the Red{nbsp}Hat root certificates and start the Minikube
cluster.

. Download the Red{nbsp}Hat current root certificates to the proper folder:
+
[source,bash]
----
mkdir -p $HOME/.minikube/certs/
wget -O $HOME/.minikube/certs/RH-IT-Root-CA.crt https://certs.corp.redhat.com/certs/Current-IT-Root-CAs.pem
----
+
[TIP]
====
Your system may need to trust the Red{nbsp}Hat self-signed certificates as well. See the
link:https://source.redhat.com/groups/public/identity-access-management/it_iam_pki_rhcs_and_digicert/faqs_new_corporate_root_certificate_authority[FAQ on internal certificates]
for installation instructions.
====

. Create the Minikube cluster:
+
[source,bash]
----
minikube start \
  --driver=kvm2 \
  --kubernetes-version=1.26.1 \
  --cpus=4 --memory=6g \
  --disk-size=30GB --embed-certs
----
+
[IMPORTANT]
====
MacOS users change the driver to `hyperkit` (`--driver=hyperkit`).
====

== Installing Agogos in Development Mode
These commands install Tekton, Knative Eventing, and the Agogos
CustomResourceDefinitions, as well as the Agogos Webhooks. They also create
self-signed certificates to encrypt the Agogos webhooks endpoint. These
certificates are automatically used by Agogos.

. Clone the
link:https://gitlab.cee.redhat.com/agogos/agogos[Agogos]
repository
. In the root folder of the cloned repository compile the project using Maven:
+
[source,bash]
----
./mvnw clean package -D skipTests
----

. Create an alias [command]`agogosctl-dev` to execute the development Java jar file:
+
[source,bash]
----
alias agogosctl-dev="java -jar ${PWD}/cli/target/quarkus-app/quarkus-run.jar"
----
+
Make sure your alias does not contain the `PWD` variable:
+
[source,bash]
----
alias agogosctl-dev
----

. Make sure you are connected to the Minikube cluster updating your context:
+
[source,bash]
----
minikube update-context
----

. Install Agogos on the Minikube cluster using the `dev` profile:
+
[source,bash]
----
QUARKUS_PROFILE=dev agogosctl-dev adm install --profile dev
----
. Forward the Knative Eventing service to the port `8111` in `localhost`:
+
[source,bash]
----
kubectl -n knative-eventing port-forward service/broker-ingress 8111:http
----

== Running Agogos
When you install Agogos in development mode you need to run the different
components locally. This makes development faster, as you don't need to build
images to test your changes. You need to keep the following commands running in
separate shells (you can press 'q' to exit their processes):

. Open a new shell and run the operator:
+
[source,bash]
----
./mvnw quarkus:dev -pl operator -am
----

. Open a new shell and run the webhooks:
+
[source,bash]
----
./mvnw quarkus:dev -pl webhooks -am
----

. Open a new shell and run the interceptors:
+
[source,bash]
----
./mvnw quarkus:dev -pl interceptors -am
----

Quarkus runs the debugger on port `5005` by default. As we are running three
instances of Quarkus, two of them do not start in debug mode. The following error
is printed in their logs, but the application continues running correctly:

[source,text]
----
[ERROR] Port 5005 in use, not starting in debug mode
----

To start every instance in debug mode, change the debug port. See 
link:https://quarkus.io/guides/maven-tooling#debugging[Maven Tooling - Debugging]
for more information.

[TIP]
====
You can start Agogos directly from Visual Studio Code, see the
xref:ide.adoc[IDE guide].
====

== Keeping Agogos Updated
Delete the Minikube cluster and start this guide again to update Agogos.

== Installing a Builder
After installing Agogos, you need to install a Builder in order to build
Components.

. Install the Sample Builder in the `agogos` namespace:
+
[source,bash]
----
kubectl -n agogos apply -f docs/modules/developer-guide/examples/development-mode/sample-builder.yaml
----

. Initialize the work namespace (for example `tests`) passing `sample-builder`
as an extension to be installed:
+
[source,bash]
----
QUARKUS_PROFILE=dev agogosctl-dev adm init --namespace tests --extensions sample-builder
----

== Building Components
. Change your current `kubectl` namespace to your work namespace (for example `tests`),
so the [command]`agogosctl` command works properly:
+
[source,bash]
----
kubectl config set-context --current --namespace tests
----

. Create the sample components:
+
[source,bash]
----
kubectl apply -f docs/modules/developer-guide/examples/development-mode/components.yaml
----

. List them using the `agogosctl`:
+
[source,bash]
----
agogosctl-dev components list
----
+
[source,bash]
----
NAME          STATUS    CREATED
sample-1      Ready     YYYY-MM-DD HH:MM:SS
sample-2      Ready     YYYY-MM-DD HH:MM:SS
sample-3      Ready     YYYY-MM-DD HH:MM:SS
----

. Build the `sample-1` component:
+
[source,bash]
----
agogosctl-dev components build sample-1
----
+
[source,bash]
----
💖 About

Name:       sample-1-cn2rj

🎉 Status

Status:     Running
Reason:     Build is running
Created:    YYYY-MM-DD HH:MM:SS
Started:    YYYY-MM-DD HH:MM:SS
Finished:   N/A
Duration:   0 minute(s)
----

. List the builds. After a while, all three components should have finished building:
+
[source,bash]
----
agogosctl-dev builds list
----
+
[source,bash]
----
NAME                STATUS       CREATED
sample-1-cn2rj      Finished     YYYY-MM-DD HH:MM:SS
sample-2-z22dj      Finished     YYYY-MM-DD HH:MM:SS
sample-3-mwv9q      Finished     YYYY-MM-DD HH:MM:SS
----

== Executing Groups

. Apply the Components and Group:
+
[source,bash]
----
kubectl apply -f docs/modules/developer-guide/examples/development-mode/group.yaml
----

. Execute the Group:
+
[source,bash]
----
agogosctl-dev group execute group-1
----
+
[source,bash]
----
💖 About

Name:       group-1-s95mg

Components: Name      Status  Started  Completed  Duration
            sample-4  New     N/A      N/A
            sample-5  New     N/A      N/A

🎉 Status

Status:     Running
Reason:     N/A
Created:    YYYY-MM-DD HH:MM:SS
Started:    YYYY-MM-DD HH:MM:SS
Finished:   N/A
Duration:   0 minute(s)
----

. After a while, the Group Components and their dependents should have finished running:
+
[source,bash]
----
agogosctl-dev builds list
----
+
[source,bash]
----
NAME               STATUS       CREATED
sample-4-wj5zn     Finished     YYYY-MM-DD HH:MM:SS
sample-5-qfnxt     Finished     YYYY-MM-DD HH:MM:SS
sample-6-cjn6q     Finished     YYYY-MM-DD HH:MM:SS
----

== Additional Resources

* xref:builders.adoc[]
* xref:pipelines.adoc[]
