---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: components.cpaas.redhat.com
spec:
  group: cpaas.redhat.com
  names:
    kind: Component
    listKind: ComponentList
    plural: components
    singular: component
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Component is the Schema for the components API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: ComponentSpec defines the desired state of Component
              properties:
                data:
                  additionalProperties:
                    type: string
                  description:
                    "Additional data containing the information about the Component.
                    It can be metadata as well as source coordinates.
                    This content needs to be supported by the particular builder
                    used to build this component. Builder defines schema that this
                    content is checked against."
                  type: object
                builder:
                  description: Builder used to build this component
                  type: string
              required:
                - "data"
                - "builder"
            status:
              description: ComponentStatus defines the observed state of Component
              properties:
                lastUpdate:
                  format: date-time
                  type: string
                reason:
                  type: string
                status:
                  default: New
                  enum:
                    - New
                    - Initializing
                    - Ready
                    - Failed
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          jsonPath: .status.status
          type: string
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
