quarkus:
  http:
    port: 7070
  log:
    syslog:
      truncate: false
  index-dependency:
    operatorsdk:
      group-id: "io.javaoperatorsdk"
      artifact-id: "operator-framework-core"

  banner:
    enabled: true
    path: "banner.txt"

"%dev":
  kubernetes:
    # Default storage class name in minikube
    storage-class: "standard"

  quarkus:
    log:
      category:
        "com.redhat.cpaas":
          level: DEBUG

    kubernetes-client:
      trust-certs: true

"%prod":
  quarkus:
    # log:
    #   category:
    #     "io.javaoperatorsdk.operator.processing":
    #       level: WARN
    #     "io.fabric8.kubernetes.client.informers.cache":
    #       level: WARN

    # TODO: change this
    kubernetes-client:
      trust-certs: true
