---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.cpaas.redhat.com
spec:
  group: cpaas.redhat.com
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Pipeline is the Schema for the pipeline API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of the Pipeline
              properties:
                group:
                  type: string
                  description: Name of the Group the Pipeline should run with
                stages:
                  type: array
                  description: List of stages to run in order
                  items:
                    type: object
                    description: Stage reference with required configuration
                    properties:
                      name:
                        type: string
                        description: Name of the stage to run
                      config:
                        type: object
                        description: "Additional configuration properties passed to the stage implementation"
                        additionalProperties:
                          type: string
                    required:
                      - "name"
              required:
                - "stages"
          type: object
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Group
          jsonPath: .spec.group
          type: string
        - name: Stages
          type: string
          jsonPath: .spec.stages[]
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
