---
apiVersion: v1
kind: Service
metadata:
  name: agogos-webhooks
  namespace: agogos
  labels:
    app.kubernetes.io/component: webhooks
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
spec:
  ports:
    - name: http
      port: 80
      targetPort: 7080
    - port: 443
      protocol: TCP
      name: https
      targetPort: 8443
  type: ClusterIP
  selector:
    app.kubernetes.io/component: webhooks
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agogos-webhooks
  namespace: agogos
  labels:
    app.kubernetes.io/component: webhooks
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhooks
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: agogos
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webhooks
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: agogos
    spec:
      containers:
        - name: webhooks
          image: quay.io/cpaas/agogos-poc-webhooks:devel
          imagePullPolicy: Always
          env:
            - name: QUARKUS_HTTP_SSL_CERTIFICATE_FILE
              value: /certs/tls.crt
            - name: QUARKUS_HTTP_SSL_CERTIFICATE_KEY_FILE
              value: /certs/tls.key
          volumeMounts:
            - name: certs
              mountPath: "/certs"
              readOnly: true
          ports:
            - containerPort: 7080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 7080
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "800m"
      volumes:
        - name: certs
          secret:
            secretName: webhooks-cert
      serviceAccount: agogos-webhooks
