= Build Artifacts

== Overview
Artifacts are output files of a Build. Every Build can define *zero or more*
artifacts.

Artifacts are important for Pipelines that work on the output of Builds.
Artifacts together with
xref:builds/results.adoc[Build Results]
provide required information so that other Pipelines can utilize
the output of a previous Build.

There are two types of artifacts:

. Local artifacts -- produced as part of the Build process in the Builder
  Pod and not uploaded anywhere,
. External artifacts -- could be either:
.. produced locally (just like local artifacts), but uploaded to an external
   storage, or
.. produced by an external system and stored externally (such as in an image
   registry or Maven repository).

In case of external artifacts, Agogos usually does not have to store them
internally as well. What Agogos needs to do is to have pointers to these files.
This can be achieved in two ways:

. Using
  xref:builds/results.adoc[Build results]
  in case there is not much data, or
. Storing this information in a file (or files!) which describe the output.

[NOTE]
====
Generation of Build results is out of control of a user -- it is the Builder
implementation that provides this content. Please refer to the particular
Builder implementation documentation.
====

For local artifacts we need to do more -- we need to store these files.
Agogos does not define the file type of the artifact, it can be anything:
a binary or a text file. Agogos does not investigate these files.

== Defining Artifacts
It is the responsibility of the developer to define which files from a Build
are saved.

== Artifact Handlers
Artifact handlers have two responsibilities:

. Storing artifacts in (potentially long-living) storage.
. Retrieving artifacts from storage.

Artifact handlers are run as part of a Build process.
