---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: componentgroups.cpaas.redhat.com
spec:
  group: cpaas.redhat.com
  names:
    kind: ComponentGroup
    listKind: ComponentGroupList
    plural: componentgroups
    singular: componentgroup
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Group is the Schema for the groups API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of Group
              properties:
                components:
                  type: array
                  description: List of the Components
                  items:
                    type: string
                    description: Name of the Component
              required:
                - "components"
          type: object
      served: true
      storage: true
