---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelineruns.cpaas.redhat.com
spec:
  group: cpaas.redhat.com
  names:
    kind: PipelineRun
    listKind: PipelineRunList
    plural: pipelineruns
    singular: pipelinerun
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: PipelineRun is the Schema for the builds API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of Build
              properties:
                pipeline:
                  description: "Name of the Pipeline to run"
                  type: string
              required:
                - "pipeline"
            status:
              description: PipelineRunStatus defines the observed state of PipelineRun
              properties:
                lastUpdate:
                  format: date-time
                  type: string
                reason:
                  type: string
                status:
                  default: New
                  enum:
                    - New
                    - Initializing
                    - Running
                    - Passed
                    - Failed
                    - Aborted
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          jsonPath: .status.status
          type: string
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
