---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: stages.cpaas.redhat.com
spec:
  group: cpaas.redhat.com
  names:
    kind: Stage
    listKind: StageList
    plural: stages
    singular: stage
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Stage is the Schema for the stages API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of Stage
              properties:
                task:
                  type: string
                  description: Name of the Tekton task being the implementation of the Stage.
                schema:
                  type: object
                  description: Validation definition that should be applied on the Stage configuration passed.
                  properties:
                    openAPIV3Schema:
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                      description: "OpenAPI v3 formatted validation.
                        More info: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md"
                  required:
                    - "openAPIV3Schema"
              required:
                - "task"
            status:
              description: StageStatus defines the observed state of Stage
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .metadata.labels.cpaas\.redhat\.com/phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
