= Agogos Developer Documentation Overview
CP Development Team <cp-devel@redhat.com>
:toc: left
:icons: font
:numbered:
:source-highlighter: highlightjs

== Scope
This page provides an overview for developers creating documentation for
the Agogos system. Agogos is the Continuous Productization (CP) automated
build and delivery system for Red{nbsp}Hat products.

== References
* link:style_guide{outfilesuffix}[Agogos Documentation Style Guide]

=== Documentation Standards

* link:https://www.amazon.com/IBM-Style-Guide-Conventions-Writers-dp-0132101300/dp/0132101300[IBM Documentation Style Guide]
* link:https://gitlab.cee.redhat.com/ccs-internal-documentation/glossary-of-terms-and-conventions-for-product-documentation[Glossary of Terms and Conventions for Red Hat Product Documentation]
* link:https://redhat-documentation.github.io/modular-docs/[Red Hat Modular Documentation Reference]

== AsciiDoc
The Agogos documentation is stored in GitLab as AsciiDoc files.
AsciiDoc is a lightweight markup language that uses files with
plain-text syntax designed for humans to read that can be converted
into HTML or other output formats.

=== References
* link:https://asciidoctor.org/docs/what-is-asciidoc/[What is AsciiDoc?]
* link:https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer's Guide]
* link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference]
* link:https://redhat-documentation.github.io/asciidoc-markup-conventions/[Red Hat's AsciiDoc Markup Style Sheet]

=== Rendering Individual Pages
The [filename]`asciidoctor` software reads and parses text written in the
AsciiDoc syntax, then produces HTML files or other supported output formats.

[NOTE]
====
AsciiDoc content will be rendered as HTML when viewing the files in GitLab.
Thus, HTML files are not created or stored in the repository. The
[filename]`asciidoctor` command is for rendering HTML locally for testing.
====

To install [filename]`asciidoctor` on Fedora or RHEL:

----
sudo dnf install -y asciidoctor
----

To create HTML files on your local system:

----
asciidoctor <name>.adoc
----

There are also Integrated Development Environments (IDEs) that will render
AsciiDoc pages while editing. Check the documentation of your specific IDE
for information on enabling AsciiDoc rendering.

[IMPORTANT]
====
Final rendering of the Agogos documentation is done with Antora,
which overrides some of the AsciiDoctor formatting. Use the instructions
below to render the entire site for a final check of any changes to the
documentation.
====

=== Rendering the Entire Site
TBD
