= Manual Installation

Agogos provides a CLI to install it on the cluster together with any other
required dependencies such as Tekton or Tekton Triggers.

[WARNING]
====
We do not provide any CLI binaries to download at this moment. In order to obtain the CLI
you need to clone the Agogos repository and build it yourself:

[source,bash]
----
❯ ./mvnw package -pl cli -am
----

Afterwards it can be run like this:

[source,bash]
----
❯ java -jar cli/target/quarkus-app/quarkus-run.jar install --help
Usage: <main class> install [-hV] [-p=<profile>]
Install Agogos
  -h, --help                Show this help message and exit.
  -p, --profile=<profile>   Selected installation profile, valid values: DEV
  -V, --version             Print version information and exit.
----
====

== Development installation

To install latest development version of Agogos run this command:

[source,bash]
----
❯ java -jar cli/target/quarkus-app/quarkus-run.jar install
----

[WARNING]
====
No confirmation is required, make sure you are using the correct cluster!
====

This command will install all required dependencies and Agogos resources on
the cluster you are authenticated with.

Agogos resources will be installed in the `agogos` namespace.

At this point the operator should be starting, you can follow logs by running
this command:

[source,bash]
----
❯ kubectl logs -n agogos -lapp.kubernetes.io/component=operator,app.kubernetes.io/part-of=agogos -f
----

Congrats, Agogos is running!

// TODO: Next steps
