= Manual Installation

The `agogosctl` binary provides an `install` command to install Agogos.
This process ensures that all Agogos dependencies and resources are
installed in the correct way.

[TIP]
====
If you don't have the CLI installed, you can follow xref:getting-started:first-steps.adoc#cli[these instructions].
====

== Installation profiles

Agogos can be installed using different profiles.

* `local`
* `dev`

[NOTE]
====
In both profiles it is assumed that the user has access to the cluster and is
already logged in. You may need to have cluster admin privileges in order
to install Agogos using these profiles.
====

The difference between these profiles is *what* Agogos resources are deployed in the
cluster. For the local profile everything will be installed in-cluster, whereas
the development profile will create only required resources in-cluster leaving
to the user to start Agogos resources manually, potentially outside of the cluster.
This is useful in case of Agogos development.

[source,bash]
----
❯ agogosctl adm install --profile local
----

[WARNING]
====
No confirmation is required, make sure you are using the correct cluster!
====

This command will install all required dependencies and Agogos resources on
the cluster you are authenticated with.

NOTE: Agogos resources will be installed in the `agogos` namespace.

At this point the operator should be starting, you can follow logs by running
this command:

[source,bash]
----
❯ kubectl logs -n agogos -lapp.kubernetes.io/component=operator,app.kubernetes.io/part-of=agogos -f
----

Congrats, Agogos is running! 🎉

// TODO: Next steps
