= Agogos Development
CP Development Team <cp-devel@redhat.com>
:toc:
:icons: font
:numbered:
:source-highlighter: highlightjs

This document describes the development workflow.

== Development Environment

Agogos can run on any development environment you control as long as it meets
following basic requirements:

* Kubernetes 1.19+
* Tekton 0.16+

[NOTE]
====
You can use Minikube to develop Agogos locally. You can find
link:minikube{outfilesuffix}[Minikube setup instructions here].
====

== Resource Initialization

In order to be able to use Agogos you need to register required resources within the cluster.

WARNING: Registration of resources needs to be performed before you start the service.

=== CRD's Registration

Once you have required tools installed and running on your system the next thing
to do is to register CRD's within the system. This can be done by running this command:

[source,bash]
.Registering CRD's
----
❯ ./operator/src/main/resources/crds/apply.sh
----

NOTE: Each time after you change the CRD you need to run above command again.

=== Service Account

The `agogos` Service Account utilizes the pull secret created before to be able to fetch images from registry.

[source,yaml]
.sa.yaml
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agogos
imagePullSecrets:
  - name: quay-pull-secret
----

[source,bash]
.Secret creation
----
❯ kubectl apply -f sa.yaml
----

=== Platform Stages Registration

Currently there is only one `init` Stage that needs to be registered.
You can use the command below to do this.

[source,bash]
----
❯ kubectl apply -f ./operator/src/main/resources/stages/init/init.yaml
clusterstage.cpaas.redhat.com/init created
clustertask.tekton.dev/init created
----

== Running Agogos In The Development Mode

[source,bash]
.Compiling and installing the application
----
❯ ./mvnw install
----

You can run the Operator in dev mode that enables live coding using:

[source,bash]
.Running the Operator
----
❯ ./mvnw quarkus:dev -pl operator
----

Similarly you can run webhooks application:

[source,bash]
.Running the webhooks code
----
❯ ./mvnw quarkus:dev -pl webhooks
----

== Testing

See link:testing{outfilesuffix}[dedicated page].
