= Local Development Environment

Agogos can be developed in environments that provide following basic requirements:

* Kubernetes 1.19+
* JDK 11

[#minikube]
== Minikube

Recommended version:: Latest
Documentation:: link:https://minikube.sigs.k8s.io/docs/start/[Official installation guide].

You may want to assign more resources to your installation. In case you use `kvm2`
driver you could use this command:

[source,bash]
----
❯ minikube start --driver=kvm2 --cpus=4 --memory=6g --disk-size=30GB
----

== Installation

Please follow the xref:getting-started:installation/manual.adoc[manual installation instructions].
It is important to use the `dev` profile which allows to run Agogos resources in development mode,
outside of the cluster.

[source,bash]
----
❯ agogosctl adm install --profile dev
----

[NOTE]
====
Please note that installing Agogos using the `agogosctl` CLI will ensure proper dependencies
are installed automatically.

This includes:

* Tekton Pipelines
* Tekton Triggers
* Knative Eventing
====

== Running Agogos

Please consult the xref:development:running.adoc[running Agogos in development mode] page.

== Gotchas

[#managing-kubernetes-contexts]
=== Managing contexts

Kubernetes contexts are managed globally. This means that any time you will have
one active context.

[NOTE]
====
Kubernetes documentation references:

* link:https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[Organizing Cluster Access Using kubeconfig Files]
* link:https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/[Configure Access to Multiple Clusters]
====

After starting Minikube, the current context is switched to `minikube`. This means
that any commands executed using `kubectl` or `oc` will be run against your local
Minikube cluster.

There are many ways how multiple contexts can be managed, two of them:

1. Manage contexts with `kubectl config` commands
+
To switch to a different use the `kubectl config use-context` command.
To list all available contexts run `kubectl config get-contexts`.
2. Use separate kubeconfig files for different use cases
+
You can maintain the minikube context in a separate kubeconfig file.
This will make it possible to switch to Minikube context by setting an environment variable.
Run the below command to create (or update) your minikube context in specified file.
+
[source,bash]
----
❯ export KUBECONFIG=~/.kube/minikube.yaml
❯ minikube update-context
🎉  "minikube" context has been updated to point to 192.168.39.112:8443
💗  Current context is "minikube"
----
+
To use the Minikube context you will need to run `export KUBECONFIG=~/.kube/minikube.yaml`
in the terminal before interacting with the cluster.

== Known issues

This section describes known issues and limitations with the setup.

=== Minikube failing to start due to `PROVIDER_KVM2_ERROR`

If you see error similar to what can be found below, just start Minikube again. It will work.

[source,bash]
----
❯ minikube start
😄  minikube v1.17.1 on Fedora 33
✨  Using the kvm2 driver based on existing profile

💣  Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:

💡  Suggestion: Follow your Linux distribution instructions for configuring KVM
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2
----
