= Running Agogos

include::common:partial$draft.adoc[]

NOTE: Make sure you have xref:environment.adoc[prepared your environment] first.

== Cluster Connection

Before running Agogos, please make sure you are logged in into correct cluster.

TIP: If you use Minikube, see the xref:environment.adoc#managing-kubernetes-contexts[note about managing contexts].

== Running Agogos Operator

=== Setting Up Broker Port Forwarding

To be able to publish CloudEvents we need to expose the Broker outside of the cluster.
The `kubectl port-forward` command could be used to achieve this goal.

[source,bash]
----
❯ kubectl port-forward service/broker-ingress 8111:80 -n knative-eventing
----

== Running Webhooks

To run Webhooks application you need to run this command:

[NOTE]
====
We assume here that you have checked out the code at the `~/agogos` path. If this
is not the case, replace it with the proper one.
====

[source,bash]
.Running Webhooks
----
❯ QUARKUS_HTTP_SSL_CERTIFICATE_FILE=~/agogos/cli/target/webhooks.crt QUARKUS_HTTP_SSL_CERTIFICATE_KEY_FILE=~/agogos/cli/target/key.pem ./mvnw clean quarkus:dev -pl webhooks -am -Dquarkus.http.host=0.0.0.0
----

After running this command you should see the Agogos Webhooks running.

----
2021-05-19 12:26:27,451 INFO  [io.quarkus] (Quarkus Main Thread) agogos-webhooks 1.0-SNAPSHOT on JVM (powered by Quarkus 1.13.1.Final) started in 5.781s. Listening on: http://0.0.0.0:7080 and https://0.0.0.0:8443
2021-05-19 12:26:27,453 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-05-19 12:26:27,453 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, config-yaml, hibernate-validator, kubernetes, kubernetes-client, quarkiverse-tekton-client, resteasy, resteasy-jackson]
----

=== Running the Operator

You can run the Operator in dev mode that enables live coding using:

[source,bash]
.Running the Operator
----
❯ ./mvnw quarkus:dev -pl operator -am
----

After running this command you should see the Agogos Operator running.

----
2021-04-06 10:18:46,079 INFO  [io.jav.ope.Operator] (Quarkus Main Thread) Registered Controller: 'PipelineController_ClientProxy' for CRD: 'class com.redhat.cpaas.v1alpha1.PipelineResource' for namespaces: [all namespaces]
2021-04-06 10:18:46,080 INFO  [com.red.cpa.k8s.PlatformOperator] (Quarkus Main Thread) Starting operator
2021-04-06 10:18:46,156 INFO  [io.quarkus] (Quarkus Main Thread) agogos-operator 1.0-SNAPSHOT on JVM (powered by Quarkus 1.12.0.Final) started in 1.332s. Listening on: http://localhost:7070
2021-04-06 10:18:46,158 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-04-06 10:18:46,158 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, config-yaml, hibernate-validator, kubernetes, kubernetes-client, openshift-client, operator-sdk, quarkiverse-tekton-client, quartz, rest-client, rest-client-jackson, resteasy, resteasy-jackson, scheduler, smallrye-health]
----

[TIP]
====
To enable hot reload, visit http://localhost:7070/ and refresh the page.

This page provides a useful development UI available at http://localhost:7070/q/dev/ as well!
====
