

quarkus:
  operator-sdk:
    crd:
      generate: false

  http:
    port: 7070
  log:
    min-level: TRACE
    syslog:
      truncate: false
  index-dependency:
    #   operatorsdk:
    #     group-id: "io.javaoperatorsdk"
    #     artifact-id: "operator-framework-core"
    okhttp:
      group-id: com.squareup.okhttp3
      artifact-id: okhttp
    okio:
      group-id: com.squareup.okio
      artifact-id: okio

  banner:
    enabled: true
    path: "banner.txt"

  container-image:
    group: cpaas
    name: agogos-poc-operator
    registry: quay.io

  quartz:
    start-mode: FORCED

agogos:
  service-account: agogos
  cloud-events:
    publish: true

kubernetes:
  # Default storage class name in minikube
  storage-class: "standard"

"%dev":
  broker/mp-rest/url: http://localhost:8111
  
  #hostnameVerifier: io.quarkus.restclient.NoopHostnameVerifier

  quarkus:
    log:
      category:
        "com.redhat.agogos":
          level: TRACE
        "io.fabric8.kubernetes.client.informers.cache":
          level: WARN
        # "io.javaoperatorsdk":
        #   level: TRACE
    kubernetes-client:
      trust-certs: true

"%prod":
  broker/mp-rest/url: "http://broker-ingress.knative-eventing.svc.cluster.local"

  quarkus:
    # http:
    #   ssl:
    #     certificate:
    #       file: /server.crt
    #       key-file: /server.key
    log:
      category:
        "com.redhat.agogos":
          level: DEBUG

    # TODO: change this
    kubernetes-client:
      trust-certs: true

"%test":
  broker/mp-rest/url: http://localhost:8111
