apiVersion: agogos.redhat.com/v1alpha1
kind: ClusterStage
metadata:
  name: init
spec:
  taskRef:
    kind: ClusterTask
    name: init
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: init
spec:
  workspaces:
    - name: "pipeline"
  params:
    - name: "image"
      type: "string"
      default: "quay.io/cpaas/agogos-poc-stage-init:devel"
    - name: "resource"
      type: "string"
      description: "Coordinates of the resource that should be fetched"
  steps:
    - name: "execute"
      imagePullPolicy: "Always"
      image: "$(params.image)"
      command: ["/usr/local/bin/entrypoint"]
      args: ["$(params.resource)", "$(workspaces.pipeline.path)"]
