---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builds.agogos.redhat.com
spec:
  group: agogos.redhat.com
  names:
    kind: Build
    listKind: BuildList
    plural: builds
    singular: build
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Build is the Schema for the builds API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of Build
              properties:
                component:
                  description: "The Component name the Build refers to"
                  type: string
              required:
                - "component"
            status:
              description: Status defines the observed state of Build
              properties:
                componentSpec:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                startTime:
                  format: date-time
                  type: string
                completionTime:
                  format: date-time
                  type: string
                lastUpdate:
                  format: date-time
                  type: string
                result:
                  description: "Build result metadata"
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                reason:
                  type: string
                status:
                  default: New
                  enum:
                    - New
                    - Running
                    - Finished
                    - Failed
                    - Aborted
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Component
          jsonPath: .spec.component
          type: string
        - name: Status
          jsonPath: .status.status
          type: string
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
