---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: executions.agogos.redhat.com
spec:
  group: agogos.redhat.com
  names:
    kind: Execution
    listKind: ExecutionList
    plural: executions
    singular: execution
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Execution is the Schema for the executions API
          properties:
            apiVersion:
              type: string
            kind:
              description:
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of Execution
              properties:
                group:
                  type: string
                components:
                  type: object
                  additionalProperties: 
                    type: object
                    properties:
                      name: 
                        type: string
                      status:
                        description: Status defines the observed state of Build
                        properties:
                          startTime:
                            format: date-time
                            type: string
                          completionTime:
                            format: date-time
                            type: string
                          reason:
                            type: string
                          lastUpdate:
                            format: date-time
                            type: string
                          status:
                            default: New
                            enum:
                              - New
                              - Running
                              - Finished
                              - Failed
                              - Aborted
                            type: string
                        type: object
                groups:
                  type: object
                  additionalProperties: 
                    type: object
                    properties:
                      name: 
                        type: string
                      status:
                        description: Status defines the observed state of Build
                        properties:
                          startTime:
                            format: date-time
                            type: string
                          completionTime:
                            format: date-time
                            type: string
                          lastUpdate:
                            format: date-time
                            type: string
                          status:
                            default: New
                            enum:
                              - New
                              - Running
                              - Finished
                              - Failed
                              - Aborted
                            type: string
                        type: object
                pipelines:
                  type: object
                  additionalProperties: 
                    type: object
                    properties:
                      name: 
                        type: string
                      status:
                        description: Status defines the observed state of Build
                        properties:
                          startTime:
                            format: date-time
                            type: string
                          completionTime:
                            format: date-time
                            type: string
                          lastUpdate:
                            format: date-time
                            type: string
                          status:
                            default: New
                            enum:
                              - New
                              - Running
                              - Finished
                              - Failed
                              - Aborted
                            type: string
                        type: object
              anyOf:
                - required: ["components"]
                - required: ["groups"]
                - required: ["pipelines"]
            status:
              description: Status defines the observed state of Build
              properties:
                startTime:
                  format: date-time
                  type: string
                completionTime:
                  format: date-time
                  type: string
                lastUpdate:
                  format: date-time
                  type: string
                status:
                  default: New
                  enum:
                    - New
                    - Running
                    - Finished
                    - Failed
                    - Aborted
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          jsonPath: .status.status
          type: string
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
