---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: submissions.agogos.redhat.com
spec:
  group: agogos.redhat.com
  names:
    kind: Submission
    listKind: SubmissionList
    plural: submissions
    singular: submission
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Submission is used to submit component builds, pipeline runs or groups executions of both
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
                generatedName:
                  type: string
                resource:
                  enum:
                    - Component
                    - Group
                    - Pipeline
                  type: string
                instance:
                  type: string
                group:
                  type: string
              required:
                - "name"
                - "resource"
                - "instance"
          type: object
      served: true
      storage: true
