---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: components.agogos.redhat.com
spec:
  group: agogos.redhat.com
  names:
    kind: Component
    listKind: ComponentList
    plural: components
    singular: component
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Component is the Schema for the components API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: ComponentSpec defines the desired state of Component
              properties:
                data:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description:
                    "Additional data containing the information about the Component.
                    It can be metadata as well as source coordinates.
                    This content needs to be supported by the particular builder
                    used to build this component. Builder defines schema that this
                    content is checked against."
                builderRef:
                  type: object
                  description: Defines the builder reference
                  properties:
                    name:
                      type: string
                      description: Name of the builder being referenced.
                    kind:
                      type: string
                      description: The kind. Can be either builder or ClusterBuilder
                source:
                  description: Information about the source code
                  type: object
                  properties:
                    handlerRef:
                      type: object
                      description: Selected SourceHandler
                      properties:
                        name:
                          type: string
                          description: Name of the SourceHandler
                    data:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      description: "Additional data that should be passed to the SourceHandler"
                  required: ["handlerRef"]

              required:
                - "data"
                - "builderRef"
            status:
              description: ComponentStatus defines the observed state of Component
              properties:
                lastUpdate:
                  format: date-time
                  type: string
                reason:
                  type: string
                status:
                  default: New
                  enum:
                    - New
                    - Initializing
                    - Ready
                    - Failed
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          jsonPath: .status.status
          type: string
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
