---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: triggers.agogos.redhat.com
spec:
  group: agogos.redhat.com
  names:
    kind: Trigger
    listKind: TriggerList
    plural: triggers
    singular: trigger
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Trigger schema
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: State of Trigger
              properties:
                events:
                  type: array
                  description: List of events that fires the Trigger
                  items:
                    type: object
                    description: Event definition that fires the Triggers

                    properties:
                      cel:
                        type: object
                        properties:
                          filter:
                            type: string
                            description: "Event filter using the CEL language: https://tekton.dev/docs/triggers/cel_expressions/"
                        required: ["filter"]
                      component:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the Component which builds should be watched
                        required: ["name"]
                      group:
                        type: object
                        properties:
                          name:
                            type: string
                            description: The name of the ComponentGroup which builds should be watched
                        required: ["name"]
                      pipeline:
                        type: object
                        properties:
                          name:
                            type: string
                            description: "The name of the Pipeline which successful finish should be watched"
                        required: ["name"]
                      build:
                        type: object
                        properties:
                          filter:
                            type: string
                            description: "Event filter using the CEL language: https://tekton.dev/docs/triggers/cel_expressions/"
                        required: ["filter"]
                      timed:
                        type: object
                        properties:
                          cron:
                            type: string
                            description: "Event filter using the CEL language: https://tekton.dev/docs/triggers/cel_expressions/"
                            example: "0 15 2 * *"
                        required: ["cron"]
                    oneOf:
                      - required: ["component"]
                      - required: ["group"]
                      - required: ["cel"]
                      - required: ["pipeline"]
                      - required: ["build"]
                      - required: ["timed"]
                target:
                  type: object
                  description: "The target resource that should be created"
                  properties:
                    kind:
                      type: string
                      enum: ["Component", "Group", "Pipeline"]
                    name:
                      type: string
                    apiVersion:
                      type: string
                  required:
                    - kind
                    - name
              required:
                - events
                - target
            status:
              description: Defines the observed state of the Trigger
              properties:
                lastUpdate:
                  format: date-time
                  type: string
                reason:
                  type: string
                status:
                  default: New
                  enum:
                    - New
                    - Initializing
                    - Ready
                    - Failed
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
