---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.agogos.redhat.com
spec:
  group: agogos.redhat.com
  names:
    kind: Pipeline
    listKind: PipelineList
    plural: pipelines
    singular: pipeline
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Pipeline is the Schema for the pipeline API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of the Pipeline
              properties:
                stages:
                  type: array
                  description: List of stages to run in order
                  items:
                    type: object
                    description: Stage reference with required configuration
                    properties:
                      stageRef:
                        type: object
                        description: Stage reference
                        properties:                         
                          name:
                            type: string
                            description: Name of the stage to run
                          namespace:
                            type: string
                            description: Namespace of where the Agogos stage can be found. Defaults to the namespace of the Agogos pipeline resource.
                        required:
                          - name
                      runAfter:
                        type: array
                        items:
                          type: string
                        description: A list of stages that must finish BEFORE this stage runs
                      config:
                        type: object
                        description: "Additional configuration properties passed to the stage implementation"
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                      - "stageRef"
                dependents:
                  type: object
                  description: Dependents of this Pipeline
                  properties:
                    components:
                      type: array
                      description: List of the Components
                      items:
                        type: string
                        description: Name of the Component
                    groups:
                      type: array
                      description: List of the Groups
                      items:
                        type: string
                        description: Name of the Group
                    pipelines:
                      type: array
                      description: List of the Pipelines
                      items:
                        type: string
                        description: Name of the Pipeline
                  anyOf:
                    - required: ["components"]
                    - required: ["groups"]
                    - required: ["pipelines"]
              required:
                - "stages"
            status:
              description: ComponentStatus defines the observed state of Component
              properties:
                lastUpdate:
                  format: date-time
                  type: string
                reason:
                  type: string
                status:
                  default: New
                  enum:
                    - New
                    - Initializing
                    - Ready
                    - Failed
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          jsonPath: .status.status
          type: string
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
