---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sourcehandlers.agogos.redhat.com
spec:
  group: agogos.redhat.com
  names:
    kind: SourceHandler
    listKind: SourceHandlerList
    plural: sourcehandlers
    singular: sourcehandler
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: SourceHandler is the schema to define a handler for particular SCM type
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of SourceHandler
              properties:
                taskRef:
                  type: object
                  description: Defines the task reference
                  properties:
                    name:
                      type: string
                      description: Name of the Tekton task being the implementation of the SourceHandler.
                    kind:
                      type: string
                      description: The SourceHandler Tekton task implementation type. Can be either Task or ClusterTask. By default it is Task.
                      default: Task
                      enum:
                        - Task
                        - ClusterTask
                    url:
                      type: string
                      description: A URL to a Task definition
                  oneOf:
                    - required: ["name", "kind"]
                    - required: ["url"]
                schema:
                  type: object
                  description: Validation definition that should be applied on the SourceHandler configuration passed.
                  properties:
                    openAPIV3Schema:
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                      description: "OpenAPI v3 formatted validation.
                        More info: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md"
                  required:
                    - "openAPIV3Schema"

                workspaces:
                  type: array
                  description: "List of workspace mappings between Agogos workspaces and Task being the implementation of SourceHandler"
                  items:
                    type: object
                    properties:
                      source:
                        type: string
                        description: "Name of the Agogos exposed workspace"
                      target:
                        type: string
                        description: "Name of the target pipeline in the Task implementation"
                      subPath:
                        type: string
                        descripton: "Subpath on the source workspace that should be exposed as the target workspace"
                    required:
                      - "target"
              required:
                - "taskRef"
            status:
              description: SourceHandlerStatus defines the observed state of SourceHandler
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
