= Agogos Documentation Policies

This page provides an overview for creating documentation for Agogos.

== Overview
The Agogos documentation is written with the
link:https://asciidoc.org/[AsciiDoc]
markup language.
link:https://antora.org/[Antora]
is the site generator used to organize and provide structure to the
documentation.
link:https://lunrjs.com/[Lunr.js]
is the search engine used to provide search capabilities to the documentation.

== Style Guidelines
The Agogos documentation style guide is based on Red{nbsp}Hat and IBM style guides.
This is a non-exhaustive list of guidelines you must follow:

* Use present tense:
+
✕ When something happens, Agogos _will do_ something.
+
✓ When something happens, Agogos _does_ something.

* Use english expressions:
+
✕ E.g.
+
✓ For example

* Use _when_ when talking about events:
+
✕ _Once_ it finishes, do X.
+
✓ _When_ it finishes, do X.

* Do not assign human characteristics to inanimate objects:
+
✕ Agogos  _sees_ X, _decides_ to do X, _asks_ you for X.
+
✓ Agogos _detects_ X, _does_ X, _promtps_ you for X.

The section
link:https://www.ibm.com/docs/en/ibm-style?topic=language-grammar["Language and Grammar" from the IBM Style Guide]
contains more examples and

== Syntax Guidelines
This is a non-exhaustive list of syntax-related guidelines you must follow:

* Use `xref` to other documents:
+
✕ `++link:../my-other-page{outfilesuffix}[My Other Page]++`
+
✓  `++xref:documentation/my-other-page.adoc[My Other Page]++`

* Use `.` for numbered lists, as AsciiDoc infers the number:
+
✕ `++1. First item++`
+
✓ `++. First item++`


== Rendering the Entire Site
To render the entire site run:

----
npm ci
npx gulp
----

These two commands install the dependencies and generate the site.
link:https://gulpjs.com/[Gulp.js]
is configured to serve the site at http://localhost:4000. The process monitors
the files related with the documentation for changes and rebuilds the site when
needed.

== Additional Resources
* link:https://redhat-documentation.github.io/asciidoc-markup-conventions/[Red{nbsp}Hat AsciiDoc Markup Conventions]
* link:https://redhat-documentation.github.io/supplementary-style-guide/[Red{nbsp}Hat Supplementary Style Guide]
* link:https://redhat-documentation.github.io/modular-docs/[Red{nbsp}Hat Modular Documentation]
* link:https://www.ibm.com/docs/en/ibm-style[IBM Style (login required)]
