quarkus:
  banner:
    enabled: false
  native:
    resources:
      includes: "deployment/crds.yaml,dependencies/*.yaml"
  security:
    security-providers: "BC"

"%dev":
  quarkus:
    log:
      level: INFO
      console:
        format: "%m%n"
      category:
        "io.quarkus.kubernetes":
          level: DEBUG
        "com.redhat.agogos":
          level: DEBUG
        "io.fabric8.kubernetes.client":
          level: ERROR
        # "io.quarkus":
        #   level: "OFF"
  agogos:
    cli-profile: admin

"%prod":
  quarkus:
    # http:
    #   insecure-requests: DISABLED
    log:
      level: INFO
      console:
        format: "%m%n"
      category:
        "io.quarkus.kubernetes":
          level: ERROR
        "io.fabric8.kubernetes.client":
          level: ERROR
        "io.quarkus":
          level: "OFF"
  agogos:
    cli-profile: user


agogos:
  cloud-events:
    base-url: "http://broker-ingress.knative-eventing.svc.cluster.local"
  container-image:
    init: "quay.io/agogos/stage-init:v1"
  operator:
    container-image: "quay.io/agogos/agogos-operator:devel"
    service-account: "agogos-webhooks"
  webhooks:
    container-image: "quay.io/agogos/agogos-webhooks:devel"
    service-account: "agogos-operator"

dependencies:
  knative-eventing:
    namespace: "knative-eventing"
    version: "v1.10.0"
    urls:
      - "https://github.com/knative/eventing/releases/download/knative-${dependencies.knative-eventing.version}/eventing-core.yaml"
      - "https://github.com/knative/eventing/releases/download/knative-${dependencies.knative-eventing.version}/in-memory-channel.yaml"
      - "https://github.com/knative/eventing/releases/download/knative-${dependencies.knative-eventing.version}/mt-channel-broker.yaml"
  tekton-pipelines:
    configmap: "config-defaults"
    namespace: "tekton-pipelines"
    version: "v0.47.2"
    urls: 
      - "https://storage.googleapis.com/tekton-releases/pipeline/previous/${dependencies.tekton-pipelines.version}/release.yaml"
  tekton-triggers:
    namespace: "tekton-pipelines"
    version: "v0.24.1"
    urls:
      - "https://storage.googleapis.com/tekton-releases/triggers/previous/${dependencies.tekton-triggers.version}/release.yaml"
      - "https://storage.googleapis.com/tekton-releases/triggers/previous/${dependencies.tekton-triggers.version}/interceptors.yaml"
