quarkus:
  banner:
    enabled: false

  security:
    security-providers: BC

  native:
    resources:
      includes: deployment/crds.yaml,dependencies/*.yaml

"%dev":
  quarkus:
    log:
      level: INFO
      console:
        format: "%m%n"
      category:
        "io.quarkus.kubernetes":
          level: DEBUG
        "com.redhat.agogos":
          level: DEBUG
        "io.fabric8.kubernetes.client":
          level: ERROR
        # "io.quarkus":
        #   level: "OFF"

  agogos:
    container-image:
      init: quay.io/cpaas/agogos-poc-stage-init:latest

"%prod":
  quarkus:
    # http:
    #   insecure-requests: DISABLED
    log:
      level: INFO
      console:
        format: "%m%n"
      category:
        "io.quarkus.kubernetes":
          level: ERROR
        "io.fabric8.kubernetes.client":
          level: ERROR
        "io.quarkus":
          level: "OFF"
