quarkus:
  banner:
    enabled: false

  security:
    security-providers: BC

  native:
    resources:
      includes: deployment/crds.yaml,dependencies/*.yaml

"%dev":
  quarkus:
    log:
      level: INFO
      console:
        format: "%m%n"
      category:
        "io.quarkus.kubernetes":
          level: DEBUG
        "com.redhat.agogos":
          level: DEBUG
        "io.fabric8.kubernetes.client":
          level: ERROR
        # "io.quarkus":
        #   level: "OFF"

"%prod":
  quarkus:
    # http:
    #   insecure-requests: DISABLED
    log:
      level: INFO
      console:
        format: "%m%n"
      category:
        "io.quarkus.kubernetes":
          level: ERROR
        "io.fabric8.kubernetes.client":
          level: ERROR
        "io.quarkus":
          level: "OFF"

agogos:
  container-image:
    init: quay.io/agogos/stage-init:v1
  webhooks:
    container-image: quay.io/cpaas/agogos-poc-webhooks:devel
    service-account: agogos-operator
  operator:
    container-image: quay.io/cpaas/agogos-poc-operator:devel
    service-account: agogos-webhooks

dependencies:
  tekton-pipeline:
    namespace: "tekton-pipelines"
    version: "v0.44.2"
    urls: 
      - "https://storage.googleapis.com/tekton-releases/pipeline/previous/${dependencies.tekton-pipeline.version}/release.yaml"
  tekton-triggers:
    namespace: "tekton-pipelines"
    version: "v0.23.0"
    urls:
      - "https://storage.googleapis.com/tekton-releases/triggers/previous/${dependencies.tekton-triggers.version}/release.yaml"
      - "https://storage.googleapis.com/tekton-releases/triggers/previous/${dependencies.tekton-triggers.version}/interceptors.yaml"
  knative-eventing:
    namespace: "knative-eventing"
    version: "v1.10.0"
    urls:
      - "https://github.com/knative/eventing/releases/download/knative-${dependencies.knative-eventing.version}/eventing-core.yaml"
      - "https://github.com/knative/eventing/releases/download/knative-${dependencies.knative-eventing.version}/in-memory-channel.yaml"
      - "https://github.com/knative/eventing/releases/download/knative-${dependencies.knative-eventing.version}/mt-channel-broker.yaml"
