---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: builders.cpaas.redhat.com
spec:
  group: cpaas.redhat.com
  names:
    kind: Builder
    listKind: BuilderList
    plural: builders
    singular: builder
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Builder is the Schema for the builders API
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
              description: Defines the desired state of Builder
              properties:
                task:
                  type: string
                  description: Name of the Tekton task being the implementation of the builder.
                schema:
                  type: object
                  description: Validation definition that should be applied on the Component's data passed to the builder.
                  properties:
                    openAPIV3Schema:
                      type: object
                      description: "OpenAPI v3 formatted validation.
                        More info: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md"
                      additionalProperties: true
                  required:
                    - "openAPIV3Schema"
              required:
                - "task"
            status:
              description: BuilderStatus defines the observed state of Builder
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
