apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: sample
spec:
  pre:
    - handlerRef:
        name: git-v1
      params:
        url: https://github.com/quarkusio/quarkus-quickstarts.git
        revision: main

  build:
    builderRef:
      kind: Builder
      name: maven-v2

    params:
      CONTEXT_DIR: getting-started
      GOALS:
        - "package"

  post:
    - handlerRef:
        name: volume-v1

      params:
        volume: artifact-storage
        config:
          - id: quarkus-run
            glob: getting-started/target/quarkus-app/**
