---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: default
  namespace: default
spec:
  serviceAccountName: agogos-el
  namespaceSelector:
    matchNames:
      - default
