---
apiVersion: agogos.redhat.com/v1alpha1
kind: Stage
metadata:
  name: write-1
spec:
  taskRef:
    name: write-task
  schema:
    openAPIV3Schema:
      required: [text]
      properties:
        text:
          type: string
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Stage
metadata:
  name: write-2
spec:
  taskRef:
    name: write-task
  schema:
    openAPIV3Schema:
      required: [text]
      properties:
        text:
          type: string
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Stage
metadata:
  name: read
spec:
  taskRef:
    name: read-task
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: write-task
spec:
  workspaces:
  - name: pipeline
  - name: stage
  params:
  - name: config
    type: string
  steps:
  - name: execute
    image: registry.access.redhat.com/ubi9-minimal:9.2
    imagePullPolicy: Always
    script: |
      #!/bin/sh -e
      echo "$1" >> $(workspaces.stage.path)/a-simple-file
    args:
    - "$(params.config)"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read-task
spec:
  workspaces:
  - name: pipeline
  - name: stage
  params:
  - name: config
    type: string
  steps:
  - name: execute
    image: registry.access.redhat.com/ubi9-minimal:9.2
    imagePullPolicy: Always
    script: |
      #!/bin/sh -e
      ls -lR $(workspaces.pipeline.path)
      echo "Exiting with an error for teaching purposes"
      exit 1
