= Builders

Builders are responsible for building
xref:components.adoc[Components].

Builders registered in the system influence what Component types
can be added to the system. It is because when defining a Component
it references the Builder that should be used to build it.

You can see an example of such reference below:

[source,yaml]
----
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: sample
spec:
  build:
    builderRef:
      kind: Builder
      name: maven-v2

    params:
      MAVEN_IMAGE: "quay.io/quarkus/centos-quarkus-maven:21.1-java11"
      GOALS:
        - "package"
----

== Implementation

Builder implementations are **Tekton Tasks**.

In the simplest case to register a Builder in the system the particular
Tekton Tasks needs to be registered as well together with the `Builder`
resource that would expose the Task within Agogos.

[source,yaml]
----
apiVersion: agogos.redhat.com/v1alpha1
kind: Builder
metadata:
  name: maven-v2
  labels:
    app.kubernetes.io/part-of: agogos
    app.kubernetes.io/component: builder
    app.kubernetes.io/instance: maven
    app.kubernetes.io/version: v2
spec:
  taskRef:
    name: maven-v2
----

== Workspaces and Artifacts

Each Builder has a single workspace assigned. This is the place
where all of the files related to building the resource is stored.

Workspaces are cleaned up after the build process is finished.
This means that artifacts produced by the Builder needs to be stored
outside of the workspace.

Some Builders will upload artifacts automatically, some don't.
In case of a Builder producing only local artifacts,
xref:handlers.adoc[Handlers]
can be used to ensure artifacts can be copied to some storage (volume, S3, registry, etc).
