= Components

Agogos' Components are resources that represent a buildable object. They
require an Agogos' Builder. Components pass parameters to Builders to modify
their behaviour.

A resource file defining a Component looks like this:

[source,yaml]
----
---
kind: Component
metadata:
  name: my-component
spec:
  build:
    builderRef:
      name: my-builder
    params:
      key: value
----

When a Component is created, Agogos creates a Tekton Pipeline associated with
it that contains the proper steps defined by the Builder. Every time the Component
is changed, its Tekton Pipeline is updated.

== Builders
Agogos' Builders are resources that wrap a Tekton Task and provide
schema validation for Components. When a Component is created its `params` are
validated against the Builder's `spec.schema.openAPIV3Schema` key,
rejecting their creation if the validation fails. Builders validate Component's
`spec.build.params`.

A resource file for a Builder looks like this:

[source,yaml]
----
---
kind: Builder
metadata:
  name: my-builder
spec:
  taskRef:
    name: my-builder-task # Task in the current namespace
  schema:
    openAPIV3Schema:
      required: [key]
      properties:
        key:
          type: string
----

An example resource file for a Component that matches the above schema would
look like this:

[source,yaml]
----
---
kind: Component
metadata:
  name: my-component
spec:
  build:
    builderRef:
      name: my-builder
    params:
      key: value
----

== Builds
Agogos' Builds are resources that represent a single build for a Component. When
a Build resource is created, a Tekton PipelineRun is created too. The Tekton
PipelineRun references the Tekton Pipeline associated with the Component of the
Build.

[WARNING]
====
Do not create Builds directly as there are intermediate steps that may need to
happen. See
xref:submissions.adoc[].
====

[source,yaml]
----
---
kind: Build
metadata:
  generatename: my-component-
spec:
  component: my-component
----

Builds have in their `status` information about the Component and its
associated Tekton PipelineRun.

[IMPORTANT]
====
To reduce resource consumption, Agogos removes Tekton PipelineRuns when they
complete successfully. This removes the Tekton PipelineRun pods from the namespace.
====

== Pre and Post Stages
Components' can be enhanced with
xref:pipelines.adoc[Agogos Stages]
that execute before and after the Builder. A Component can define stages in its
`pre` and `post` keys:

[source,yaml]
----
---
kind: Component
metadata:
  name: my-component
spec:
  pre:
  - stageRef:
      name: my-pre-stage
    config:
      key: value
  build:
    builderRef:
      name: my-builder
    params:
      key: value
  post:
  - stageRef:
      name: my-post-stage
    config:
      key: value
----

Using Agogos Stages within a Component provides flexibility to run arbitrary
processes for your build. For example you may need to run a certain tool
and submit its results to version control or to download and submit dependencies.

== Additional Resources

* xref:developer-guide:builders.adoc[]
* link:https://gitlab.cee.redhat.com/agogos/agogos/-/blob/main/cli/src/main/resources/deployment/crds/[Agogos CustomResourceDefinitions]
* link:https://gitlab.cee.redhat.com/agogos/agogos/-/tree/main/core/src/main/java/com/redhat/agogos/core/v1alpha1[Agogos custom resources in Java]
* link:https://gitlab.cee.redhat.com/agogos/agogos/-/tree/main/operator/src/main/java/com/redhat/agogos/operator/k8s/controllers[Agogos controllers in Java]
