= Handlers

Handlers are an extension mechanism for the build process. Handlers are defined on the
xref:components.adoc[Component]
level and are run before or after the build.

A potential use cases for Handlers include:

* obtaining source code required for the build execution (*pre handler*)
* storing built artifacts in some particular storage after the build is done (*post handler*)

Handlers have full access to a volume shared with other handlers and the
xref:builders.adoc[Builder]
itself.

====
Below you can see an example workflow where the Handler is fetching the source code
from a repository and providing it to the Builder.

[graphviz,sourcehandler,svg]
....
digraph G {
rankdir="LR";
newrank=true;

graph [fontname="helvetica",ranksep=1,nodesep=0.5];
node [fontname="helvetica",shape="box",style="rounded",fontsize="12"];
edge [fontname="helvetica",arrowsize="1",penwidth="1",fontsize="10"];

start [label="",shape="circle",color="#000000",penwidth="2",width="0.2"];
handler [label="(Source) handler",color="#a83232",penwidth="2"];
stop [label="",shape="circle",color="#000000",penwidth="2",width="0.2",fillcolor="#000000"];
repository [label="Source repository",color="#a83232",penwidth="2"];
builder [style="",label="Builder",color="#328da8",penwidth="2",shape="parallelogram",fixedsize="true",width="1.5",height="0.8"];

{ rank=same; repository; builder; }

start -> handler;
repository -> builder [style="dashed",color="#888888",label="Source code"];
handler -> repository [style="dashed",color="#888888"];
handler -> builder;
builder -> stop;
}
....

[NOTE]
====
This is a simplified view of the process. In reality there a volume shared
by the Handler and Builder. Fetched data is stored there so that Builder can
access it later.
====

== Example Handler Usage

In the example found below we can see two handlers:

1. Pre handler which is responsible for obtaining the source code from a git repository
2. Post handler which stores selected artifacts on a volume within the cluster

[source,yaml]
----
include::example$component.yaml[]
----
