---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: sample-1
spec:
  dependents:
    components:
      - sample-2
  build:
    builderRef:
      name: sample-builder
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: sample-2
spec:
  dependents:
    components:
      - sample-3
  build:
    builderRef:
      name: sample-builder
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: sample-3
spec:
  build:
    builderRef:
      name: sample-builder
