---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: dummy-1-a
spec:
  build:
    builderRef:
      kind: Builder
      name: dummy-v1
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: dummy-1-b
spec:
  build:
    builderRef:
      kind: Builder
      name: dummy-v1
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Group
metadata:
  name: group-1
spec:
  components:
  - dummy-1-a
  - dummy-1-b
  dependents:
    components:
    - dummy-2
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: dummy-2
spec:
  dependents:
    components:
    - dummy-3
  build:
    builderRef:
      kind: Builder
      name: dummy-v1
---
apiVersion: agogos.redhat.com/v1alpha1
kind: Component
metadata:
  name: dummy-3
spec:
  build:
    builderRef:
      kind: Builder
      name: dummy-v1
