---
apiVersion: agogos.redhat.com/v1alpha1
kind: Builder
metadata:
  name: sample-builder
spec:
  taskRef:
    resolver: cluster
    params:
      - name: kind
        value: task
      - name: namespace
        value: agogos
      - name: name
        value: sample-builder-task
  schema:
    openAPIV3Schema:
      properties:
        property:
          type: string
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-builder-task
spec:
  workspaces:
    - name: pipeline
    - name: stage
  params:
    - name: params
      type: string
  results:
    - name: data
      description: JSON formatted string
  volumes:
    - name: config
      configMap:
        name: sample-builder-config
        optional: true
  steps:
    - name: execute
      image: registry.access.redhat.com/ubi9/python-39:1
      imagePullPolicy: Always
      script: |
        #!/bin/python3
        import argparse
        import json
        from pathlib import Path

        parser = argparse.ArgumentParser()
        parser.add_argument("--params")
        parser.add_argument("--results-path")
        parser.add_argument("--output-path")
        args = parser.parse_args()

        print(args.output_path)
        print(args.results_path)
        print(args.params)

        config_path = Path("/config/sample-builder-config.json")
        if config_path.exists():
            config = json.loads(config_path.read_text())
            print(config)

        # This is required to end successfuly
        with open(args.results_path, "w+") as results_file:
            print(json.dumps({"success": True}), file=results_file)
      args:
        - "--output-path=$(workspaces.pipeline.path)"
        - "--results-path=$(results.data.path)"
        - "--params=$(params.params)"
      volumeMounts:
        - name: config
          mountPath: /config
