= Build Stage Development Tutorial
CP Development Team <cp-devel@redhat.com>
:toc:
:icons: font
:numbered:
:source-highlighter: highlightjs

WARNING: #This content is outdated and needs to be updated#

Builder consists from following pieces:

1. Container image(s)
2. Tekton Task definition (together with any optional resources)
3. Builder definition

== Container image

It's up to the Builder maintainer how the container image implementing the Builder is created
although general [OpenShift guidelines for creating images](https://docs.openshift.com/container-platform/4.5/openshift_images/create-images.html)
should be followed.

Builder container image should contain every tool to successfully execute a build of
the passed Component definition.

== Tekton Task definition

Next step is to create a Tekton Task which is responsible for:

1. Exposing the container image as a Tekton Task
2. Implement the platform API which will be used to pass data to container

Minimal template:

[source,yaml]
----
apiVersion: "tekton.dev/v1beta1"
kind: "Task"
metadata:
  name: "[TASK_NAME]"
spec:
  workspaces:
    - name: "shared"
    - name: "results"
  params:
    - name: "component"
      type: "string"
      description: "JSON-formatted component data"
  steps:
    - name: "execute"
      image: "[IMAGE]"
      command: ["[PATH_TO_COMMAND_TO_RUN]"]
      args: ["[ARG1]", "$(params.component)", "$(workspaces.results.path)"]
----

TIP: See link:stage-api{outfilesuffix}[the API definition for Tekton Tasks].

This can be extended so that it fits the requirements of the Builder.
Builder developer knows what is the best way to pass the data and run the specific tool.
Tekton Task is just a way to make it in a structured way following the requirements
of the platform, so that data passed by the platform could be understood by the Builder
implementation.

=== Additional resources

Builder can require additional resources. These should be made available before the Task
execution. Preferable additional resource definitions should be stored together with the
Task definition so that it creates a *package*.

Resource names should be prefixed with the Builder name.
For example a `brew` Builder can require a secret which name is `keytab`.
Within the system it should be registered under the `brew-keytab` name.

Similar applies to any other resources like ConfigMap's.

== Builder definition

The last step is to create a Builder definition.

Builder responsibilities:

1. Exposing the Tekton Task within the platform
2. Providing a place to define supported Component types (validation)

Minimal template:

[source,yaml]
----
apiVersion: cpaas.redhat.com/v1alpha1
kind: Builder
metadata:
  name: "[BUILDER_NAME]"
spec:
  task: "[TEKTON_TASK_NAME]"
  schema:
    openAPIV3Schema:

      # Custom schema below
      type: object
      properties:
        sourceRepo:
        description: "Source repository in following format: [namespace]/[repository-name]"
        type: string
        sourceRef:
        description: "Git reference (branch) to use when building the component"
        type: string
----
