= Stage API
CP Development Team <cp-devel@redhat.com>
:toc:
:icons: font
:numbered:
:source-highlighter: highlightjs

WARNING: #This content is outdated and needs to be updated#

Builders are implemented as Tekton Tasks. To be able to orchestrate building components
an API was established to define the contract between the platform and the
implementation of the Builder (Tekton Task).

== Workspaces

TIP: Tekton docs: https://tekton.dev/docs/pipelines/tasks/#specifying-workspaces

Following workspaces are available:

* `shared`
* `results`

=== `results` workspace

This workspace is used to store results of the build. By results we mean any metadata
information produced by particular Builder when building the Component. This could include:

* Artifact metadata in Builder-specific format.
* Logs

Below you can find guidelines about what should and what shouldn't be stored:

1. Stored files should be small. This is not the place where artifacts built by the
Builder should be saved.
2. Refrain from storing binary files.

=== `shared` workspace

The `shared` workspace can be used to share data between Steps within the Task.

=== Definition

[source,yaml]
----
spec:
  workspaces:
    - name: "shared"
    - name: "results"
----

== Parameters

TIP: Tekton docs: https://tekton.dev/docs/pipelines/tasks/#specifying-parameters

Following parameters will be passed to every Builder task:

* `component`

The `component` parameter contains all the metadata that describes:

1. What is the component (metadata)
2. How to build it (source coordinates)

It is responsibility of the Task to parse the data an use it in a way it is designed.

=== Definition

[source,yaml]
----
spec:
  params:
    - name: "component"
      type: "string"
      description: "JSON-formatted component data"
----

== Results

#Work in progress#

TIP: Tekton docs: https://tekton.dev/docs/pipelines/tasks/#emitting-results

It's up to the Task developer to define and populate results of the task.

Results must be small (<4kB of data). If there is a requirement to store bigger data, workspace should be used to do so and result should have a pointer to it.

=== Best practices

* If possible Build metadata should be stored within the system (usage of results and workspaces). Querying information about results should not involve external systems.
