= Service Accounts

The Service Accounts used for Agogos are:

* `agogos-bot-dev@IPA.REDHAT.COM`
* `agogos-bot-prod@IPA.REDHAT.COM`

Both accounts are
link:https://web.mit.edu/kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-user/What-is-a-Kerberos-Principal_003f.html[Kerberos principals].

== Authenticating
To authenticate with the Agogos, download their keytabs from the Agogos folder in the
HashiCorp Vault Red{nbsp}Hat instance:

* `agogos-bot-dev`: 
link:https://vault.corp.redhat.com:8200/ui/vault/secrets/kv2/show/sp/guilds/cp/agogos/dev/kerberos?namespace=exd[sp/guilds/cp/agogos/dev/kerberos]
* `agogos-bot-prod`:
link:https://vault.corp.redhat.com:8200/ui/vault/secrets/kv2/show/sp/guilds/cp/agogos/prod/kerberos?namespace=exd[sp/guilds/cp/agogos/prod/kerberos]

Decode the contents using base64:

[source,bash]
----
$ base64 -d agogos-bot-dev-base64.txt > agogos-bot-dev.keytab
$ base64 -d agogos-bot-prod-base64.txt > agogos-bot-prod.keytab
----

Then use `kinit` to load their tickets into your system:

[source,bash]
----
$ kinit agogos-bot-dev@IPA.REDHAT.COM -kt agogos-bot-dev.keytab
$ kinit agogos-bot-prod@IPA.REDHAT.COM -kt agogos-bot-prod.keytab
----

[TIP]
====
Delete you previous tickets with `kdestroy -A`, so your system uses the Agogos
tickets directly.
====

== Requesting The Accounts
=== GPG Key
Start by creating a GPG key, the public part is assigned to the accounts so they
can be recognized by key if needed.

1. Create a password for the key, store it on agogos Vault
2. Generate the GPG key:
+
[source,bash]
----
$ gpg --full-generate-key
----
+
Fill in the following details:
+
[source,text]
----
Real name: Agogos
Email address: cpaas-ops@redhat.com
Comment: Agogos Identity
----
3. Export the public part of the key:
+
[source,bash]
----
gpg --output public.pgp --armor --export cpaas-ops@redhat.com
----

[IMPORTANT]
====
Backup and upload the secret key and the password for it to the HashiCorp Vault.

[source,bash]
----
$ gpg --output identity.pgp --armor --export-secret-keys --export-options export-backup cpaas-ops@redhat.com
----
====

=== Requesting The Accounts
The accounts are requested using
link:https://help.redhat.com[ServiceNow].
A the time of this writing the request is called
link:https://redhat.service-now.com/help?id=sc_cat_item&sys_id=ec649e491bc74d587f9bfc8f034bcbe3[Service Account LDAP (RHDS) & IPA Support].
The details of the request are:

* Service Accounts: agogos-bot-dev, agogos-bot-prod
* Application ID: AGOG-001
* Application Authentication: LDAP/IPA
* Authentication Type: Keytab
* Any other change: IPA and LDAP shells set to `/bin/sh`

Attach the public GPG key you exported before and leave a comment like: "I have
attach a public key so you use it to create the accounts"

=== Testing
To test that the account and the details are correct, check LDAP and IPA:

[source,bash]
----
$ ldapsearch -x -b "uid=agogos-bot-dev, ou=users, dc=redhat, dc=com" | grep -i shell
$ ldapsearch -x -b "uid=agogos-bot-prod, ou=users, dc=redhat, dc=com" | grep -i shell
$ ipa user-show agogos-bot-dev | grep -i shell
$ ipa user-show agogos-bot-prod | grep -i shell
----
