quarkus:
  banner:
    enabled: true
    path: "banner.txt"
  container-image:
    group: "agogos"
    name: "agogos-webhooks"
    registry: "quay.io"
    tag: "latest"
  docker:
    dockerfile-jvm-path: "src/main/docker/Dockerfile.fast-jar"
  http:
    port: 7080
  log:
    min-level: "TRACE"
    syslog:
      truncate: false

"%test":
  quarkus:
    log:
      category:
        "com.redhat.agogos":
          level: TRACE

"%dev":
  quarkus:
    http:
      host: 0.0.0.0
      ssl:
        certificate:
          files: ["${PWD}/webhooks.crt"]
          key-files: ["${PWD}/key.pem"]
      access-log:
        enabled: true
        pattern: combined
    log:
      category:
        "com.redhat.agogos":
          level: TRACE
        # "io.javaoperatorsdk":
        #   level: TRACE

"%prod":
  # TODO: change this
  kubernetes-client:
    trust-certs: true

  quarkus:
    http:
      access-log:
        enabled: true
        pattern: combined
    log:
      category:
        "com.redhat.agogos":
          level: DEBUG
