quarkus:
  http:
    port: 7080
  log:
    min-level: TRACE
    syslog:
      truncate: false

  banner:
    enabled: true
    path: "banner.txt"

  container-image:
    group: cpaas
    name: agogos-poc-webhooks
    registry: quay.io

"%test":
  quarkus:
    log:
      category:
        "com.redhat.agogos":
          level: TRACE

"%dev":
  quarkus:
    http:
      access-log:
        enabled: true
        pattern: combined
    log:
      category:
        "com.redhat.agogos":
          level: TRACE
        # "io.javaoperatorsdk":
        #   level: TRACE

"%prod":
  # TODO: change this
  kubernetes-client:
    trust-certs: true

  quarkus:
    http:
      access-log:
        enabled: true
        pattern: combined
    log:
      category:
        "com.redhat.agogos":
          level: DEBUG
