= Agogos Development
CP Development Team <cp-devel@redhat.com>
:toc:
:icons: font
:numbered:
:source-highlighter: highlightjs

This document describes the development workflow.

== System requirements

Please make sure you have following requirements installed:

* link:https://minikube.sigs.k8s.io/docs/start/[Minikube]
** link:https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl]
* link:https://tekton.dev/docs/getting-started/#installation[Tekton]
* link:https://sdkman.io/jdks#jdk.java.net[JDK 11]

=== Known issues

==== Minikube failing to start due to `PROVIDER_KVM2_ERROR`

If you see error similar to what can be found below, just start Minikube again. It will work.

[source,bash]
----
❯ minikube start
😄  minikube v1.17.1 on Fedora 33
✨  Using the kvm2 driver based on existing profile

💣  Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:

💡  Suggestion: Follow your Linux distribution instructions for configuring KVM
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2
----

== Resource requirements

In order to be able to use Agogos you need to register required resources within the cluster.

WARNING: Registration of resources needs to be performed before you start the service.

=== Registering CRD's

Once you have required tools installed and running on your system the next thing
to do is to register CRD's within the system. This can be done by running this command:

[source,bash]
.Registering CRD's
----
❯ ./operator/src/main/resources/crds/apply.sh
----

NOTE: Each time after you change the CRD you need to run above command again.

==== Quay pull secret

To be able to use resources (stages) developed by the Agogos team you need to have access to
these images. Currently these are private and hosted in link:https://quay.io[quay.io] repository.

NOTE: You can obtain a token (password) for a bot account that has read-only access to these images.
This will make it possible to fetch them in your deployment. Please each out to one of Agogos developers
for details.

===== Secret creation

If your account has access to Agogos images you can create the pull secret by following
instruction found below. Alternatively you can use details provided by the Agogos team.

Navigate to link:https://quay.io[quay.io] and open Account Settings page. Click on the
"Generate Encrypted Password" link and enter your quay.io password. Navigate to "Encrypted
Password" and copy the value. It will be used in the command below.

[source,bash]
.Secret creation
----
❯ kubectl create secret docker-registry quay-pull-secret --docker-server=quay.io --docker-username=<username> --docker-password=<password> --docker-email=agogos@domain.com
secret/quay-pull-secret created
----

NOTE: The Secret name: `quay-pull-secret` needs to match the `imagePullSecret` name in the Service Account definition.

==== Service Account

The `agogos` Service Account utilizes the pull secret created before to be able to fetch images from registry.

[source,yaml]
.sa.yaml
----
include::inc/deployment/sa.yaml[]
----

[source,bash]
.Secret creation
----
❯ kubectl apply -f sa.yaml
----

=== Registering Platform Stages

Currently there is only one `init` Stage that needs to be registered.
You can use the command below to do this.

[source,bash]
----
❯ kubectl apply -f ./operator/src/main/resources/stages/init/init.yaml
clusterstage.cpaas.redhat.com/init created
clustertask.tekton.dev/init created
----

== Running In The Development Mode

[source,bash]
.Compiling and installing the application
----
❯ ./mvnw install
----

You can run the Operator in dev mode that enables live coding using:

[source,bash]
.Running the Operator
----
❯ ./mvnw quarkus:dev -pl operator
----

Similarly you can run webhooks application:

[source,bash]
.Running the webhooks code
----
❯ ./mvnw quarkus:dev -pl webhooks
----

== Testing

See link:testing{outfilesuffix}[dedicated page].
